import type { ComponentTokensInput } from "#modules/dtcg/types";

import components from "#config/components";
import { keys } from "objectively";

const INDENT = "  ";

/**
 * Render the generated `ComponentTokens` registry from the resolved schema.
 *
 * Every supported component is emitted as a key. Components that declare tokens
 * map to a union of their token names (the extra keys `TokenProps<T>` admits);
 * components with none map to `never`.
 */
export const generateComponentTokenTypes = (
  schema: ComponentTokensInput,
): string => {
  const elements = components.elements.map((component) => {
    const slots = schema[component];

    if (!slots || keys(slots).length === 0) {
      return `${INDENT}${component}: never;`;
    }

    const union = keys(slots)
      .map((name) => JSON.stringify(name))
      .join(" | ");

    return `${INDENT}${component}: ${union};`;
  });

  return [
    "// Generated by the `dtcg` module — do not edit.",
    "export interface ComponentTokens {",
    ...elements,
    "}",
    "",
  ].join("\n");
};
