import { defineNuxtRouteMiddleware, navigateTo } from "#app";
import { useAuth } from "./composables";

// @ts-ignore — virtual module generated by the rampart Nuxt module
import { basePath } from "#build/rampart.config.mjs";

export default defineNuxtRouteMiddleware(() => {
  const { authenticated } = useAuth();

  if (!authenticated.value) {
    return navigateTo(`${basePath}/login`, { external: true });
  }
});
