import { computed } from "vue";
import { useState, useNuxtApp, navigateTo, createError, defineNuxtRouteMiddleware } from "#app";
import type { RampartUser, RampartRole, RampartScope } from "../src/types";

// @ts-ignore — virtual module generated by the rampart Nuxt module
import { basePath, forbiddenRoute } from "#build/rampart.config.mjs";

const denyAccess = () => {
  if (forbiddenRoute) {
    return navigateTo(forbiddenRoute as string);
  }
  throw createError({ statusCode: 403, message: "Forbidden" });
};

/** Reactive auth state. Hydrates from SSR context on first call. */
export const useAuth = () => {
  const user = useState<RampartUser | null>("rampart:user", () => null);
  const initialized = useState<boolean>("rampart:initialized", () => false);

  // Hydrate from SSR payload on first server render
  if (!initialized.value && import.meta.server) {
    const nuxtApp = useNuxtApp();
    const ssrUser = nuxtApp.ssrContext?.event?.context?.user as RampartUser | undefined;
    if (ssrUser) {
      user.value = ssrUser;
    }
    initialized.value = true;
  }

  const authenticated = computed(() => user.value !== null);

  const login = () => navigateTo(`${basePath}/login`, { external: true });

  const logout = async () => {
    user.value = null;
    await navigateTo(`${basePath}/logout`, { external: true });
  };

  return {
    user,
    authenticated,
    initialized,
    login,
    logout,
  };
};

/** Check if the current user has specific roles. */
export const hasRole = (...roles: RampartRole[]): boolean => {
  const { user } = useAuth();
  if (!user.value) return false;
  const userRoles = (user.value as RampartUser & { roles?: RampartRole[] }).roles;
  if (!userRoles) return false;
  return roles.every((role) => userRoles.includes(role));
};

/** Check if the current user has specific scopes. */
export const hasScope = (...scopes: RampartScope[]): boolean => {
  const { user } = useAuth();
  if (!user.value) return false;
  const userScopes = (user.value as RampartUser & { scopes?: RampartScope[] }).scopes;
  if (!userScopes) return false;
  return scopes.every((scope) => userScopes.includes(scope));
};

/** Creates a route middleware that requires specific roles. */
export const defineRoleMiddleware = (...roles: RampartRole[]) =>
  defineNuxtRouteMiddleware(() => {
    const { authenticated } = useAuth();
    if (!authenticated.value) {
      return navigateTo(`${basePath}/login`, { external: true });
    }
    if (!hasRole(...roles)) {
      return denyAccess();
    }
  });

/** Creates a route middleware that requires specific scopes. */
export const defineScopeMiddleware = (...scopes: RampartScope[]) =>
  defineNuxtRouteMiddleware(() => {
    const { authenticated } = useAuth();
    if (!authenticated.value) {
      return navigateTo(`${basePath}/login`, { external: true });
    }
    if (!hasScope(...scopes)) {
      return denyAccess();
    }
  });
