import { defineEventHandler, getRequestPath, sendRedirect, createError } from "h3";
import type { H3Event } from "h3";
import type { RampartHandlers } from "../src/types";
import { getSession, setSession, clearSession, isCacheFresh } from "./session";

// @ts-ignore — virtual module generated by the rampart Nuxt module
import { basePath, publicRoutes, refreshThreshold, meCacheTTL } from "#build/rampart.config.mjs";

const INTERNAL_PREFIXES = ["/_nuxt/", "/__", "/api/_"];

const loginPath = `${basePath}/login`;
const logoutPath = `${basePath}/logout`;

const isPublic = (path: string): boolean => {
  if (INTERNAL_PREFIXES.some((p) => path.startsWith(p))) return true;
  if (path.startsWith(`${basePath}/`)) return true;
  return (publicRoutes as string[]).some((route: string) =>
    path === route || path.startsWith(`${route}/`),
  );
};

/**
 * Checks if the access token is near expiry and refreshes if needed.
 * Exported so API proxy routes can call it before forwarding requests.
 *
 * Updates event.context and persists to the session on success.
 * Returns true if the token is valid, false if refresh failed.
 */
export const ensureFreshToken = async (
  event: H3Event,
  handlers: RampartHandlers,
): Promise<boolean> => {
  if (!handlers.refresh) return true;

  const expiresAt = event.context.tokenExpiresAt as number | undefined;
  if (!expiresAt) return true;

  const threshold = (refreshThreshold as number) || 600000;
  if (Date.now() + threshold < expiresAt) return true;

  const tokens = await handlers.refresh(event);
  if (!tokens) return false;

  event.context.accessToken = tokens.accessToken;
  event.context.tokenExpiresAt = tokens.expiresAt;

  // Persist refreshed tokens to the session
  const session = await getSession(event);
  if (session) {
    await setSession(event, { ...session, tokens });
  }

  return true;
};

/**
 * Single entry point for auth. Handles middleware, login, logout, and token refresh.
 * Rampart owns the session and context binding — consumer provides callbacks.
 */
export const defineAuthHandlers = (handlers: RampartHandlers) =>
  defineEventHandler(async (event) => {
    const path = getRequestPath(event);

    // Login — redirect to auth provider
    if (path === loginPath) {
      return handlers.login(event);
    }

    // Callback — handle OAuth return, persist session
    if (path.startsWith(`${loginPath}/`)) {
      return handlers.callback(event, {
        setSession: (identity) => setSession(event, identity),
      });
    }

    // Logout — clear session first, then let consumer do provider cleanup
    if (path === logoutPath || path.startsWith(`${logoutPath}/`)) {
      await clearSession(event);
      await handlers.logout(event);
      return sendRedirect(event, loginPath);
    }

    // Public routes — no auth required
    if (isPublic(path)) return;

    // Read session from sealed cookie
    const session = await getSession(event);

    if (!session) {
      if (path.startsWith("/api/")) {
        throw createError({ statusCode: 401, message: "Unauthorized" });
      }
      return sendRedirect(event, loginPath);
    }

    // Use cached identity if fresh, otherwise call me() and cache the result
    const ttl = (meCacheTTL as number) ?? 300000;
    let identity = session;

    if (!isCacheFresh(session, ttl)) {
      const enriched = await handlers.me(event, session);

      if (!enriched) {
        await clearSession(event);
        if (path.startsWith("/api/")) {
          throw createError({ statusCode: 401, message: "Unauthorized" });
        }
        return sendRedirect(event, loginPath);
      }

      identity = enriched;
      await setSession(event, identity);
    }

    // Rampart owns context binding
    event.context.user = identity.user;
    if (identity.tokens) {
      event.context.accessToken = identity.tokens.accessToken;
      event.context.tokenExpiresAt = identity.tokens.expiresAt;
    }

    // Proactively refresh token if near expiry
    const tokenFresh = await ensureFreshToken(event, handlers);
    if (!tokenFresh) {
      if (path.startsWith("/api/")) {
        throw createError({ statusCode: 401, message: "Session expired" });
      }
      return sendRedirect(event, loginPath);
    }
  });
