export const useMockTable = () => {
  const store = accessMockTableStore();

  const {
    data,
    loading,
    page,
    pageSize,
    pageCount,
    total,
    sortField,
    sortDirection,
    query,
    keywords,
    match,
    facetGroups,
    selectedFacets,
    dateFilters,
    selected,
    isAllSelected,
    isIndeterminate,
    selectAllState,
    colSpan,
    columns,
    rowKey,
    dateFields,
    selectionActions,
  } = storeToRefs(store);

  return {
    data,
    loading,
    page,
    pageSize,
    pageCount,
    total,
    sortField,
    sortDirection,
    query,
    keywords,
    match,
    facetGroups,
    selectedFacets,
    dateFilters,
    selected,
    isAllSelected,
    isIndeterminate,
    selectAllState,
    colSpan,

    // Non-reactive values
    columns,
    rowKey,
    dateFields,
    selectionActions,

    // Methods
    goToPage: store.goToPage,
    sortBy: store.sortBy,
    clearFacets: store.clearFacets,
    addDateFilter: store.addDateFilter,
    removeDateFilter: store.removeDateFilter,
    clearDateFilters: store.clearDateFilters,
    toggleRow: store.toggleRow,
    toggleAll: store.toggleAll,
    clearSelection: store.clearSelection,
    sortFieldFor: store.sortFieldFor,
    isSorted: store.isSorted,
    getSortIcon: store.getSortIcon,
    isRowSelected: store.isRowSelected,
    setPageSize: store.setPageSize,
    update: store.update,
    fetch: store.fetch,
  };
};
