packages:
  - "apps/*"
  - "layers/*"
  - "packages/*"

catalog:
  nuxt: ^4.2.0
  defu: ^6.1.4
  typescript: ^5.9.3
  "reka-ui": ^2.6.0
  unocss: ^66.5.5
  "@unocss/nuxt": ^66.5.5
  "@nuxt/content": ^3.9.0
