import { defineNuxtConfig } from "nuxt/config";

// Blocks: Standalone elements
import {
  a,
  alertNote,
  alertNoteIcon,
  alertTip,
  alertTipIcon,
  alertImportant,
  alertImportantIcon,
  alertWarning,
  alertWarningIcon,
  alertCaution,
  alertCautionIcon,
  article,
  aside,
  banner,
  blockquote,
  button,
  caption,
  card,
  chip,
  code,
  del,
  em,
  fab,
  footer,
  group,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  header,
  hr,
  icon,
  img,
  input,
  kbd,
  label,
  li,
  link,
  main,
  nav,
  ol,
  p,
  pre,
  section,
  strong,
  table,
  tbody,
  td,
  th,
  thead,
  tr,
  ul,
} from "@foundation/blocks/elements";

// Blocks: Compound elements
import {
  accordion,
  avatar,
  breadcrumbs,
  checkbox,
  command,
  dialog,
  listbox,
  navigator,
  popover,
  select,
  tabs,
  tagsInput,
  tooltip,
  tree,
} from "@foundation/blocks/elements";

// Prose: Elements
import {
  attribution,
  contentAccordion,
  contentFiltersSection,
  contentGrid,
  contentSearch,
  navList,
  surround,
  toc,
} from "@foundation/prose/elements";

// Docula: App-specific elements
import { community, container, search, topbar, versionSelect } from "./elements.config";

export default defineNuxtConfig({
  compatibilityDate: "2025-11-17",
  extends: ["@foundation/prose", "@foundation/giscus"],
  modules: ["nuxt-typed-router"],
  app: {
    head: {
      title: "Docula",
      meta: [
        {
          name: "description",
          content: "Documentation site built with Foundation",
        },
      ],
    },
  },
  untheme: {
    elements: {
      // Blocks: Standalone elements
      [a.key]: a.$def,
      [alertNote.key]: alertNote.$def,
      [alertNoteIcon.key]: alertNoteIcon.$def,
      [alertTip.key]: alertTip.$def,
      [alertTipIcon.key]: alertTipIcon.$def,
      [alertImportant.key]: alertImportant.$def,
      [alertImportantIcon.key]: alertImportantIcon.$def,
      [alertWarning.key]: alertWarning.$def,
      [alertWarningIcon.key]: alertWarningIcon.$def,
      [alertCaution.key]: alertCaution.$def,
      [alertCautionIcon.key]: alertCautionIcon.$def,
      [article.key]: article.$def,
      [aside.key]: aside.$def,
      [banner.key]: banner.$def,
      [blockquote.key]: blockquote.$def,
      [button.key]: button.$def,
      [caption.key]: caption.$def,
      [card.key]: card.$def,
      [chip.key]: chip.$def,
      [code.key]: code.$def,
      [del.key]: del.$def,
      [em.key]: em.$def,
      [fab.key]: fab.$def,
      [footer.key]: footer.$def,
      [group.key]: group.$def,
      [h1.key]: h1.$def,
      [h2.key]: h2.$def,
      [h3.key]: h3.$def,
      [h4.key]: h4.$def,
      [h5.key]: h5.$def,
      [h6.key]: h6.$def,
      [header.key]: header.$def,
      [hr.key]: hr.$def,
      [icon.key]: icon.$def,
      [img.key]: img.$def,
      ...input.$defs,
      [kbd.key]: kbd.$def,
      [label.key]: label.$def,
      [li.key]: li.$def,
      [link.key]: link.$def,
      [main.key]: main.$def,
      [nav.key]: nav.$def,
      [ol.key]: ol.$def,
      [p.key]: p.$def,
      [pre.key]: pre.$def,
      [section.key]: section.$def,
      [strong.key]: strong.$def,
      [table.key]: table.$def,
      [tbody.key]: tbody.$def,
      [td.key]: td.$def,
      [th.key]: th.$def,
      [thead.key]: thead.$def,
      [tr.key]: tr.$def,
      [ul.key]: ul.$def,

      // Blocks: Compound elements
      ...accordion.$defs,
      ...avatar.$defs,
      ...breadcrumbs.$defs,
      ...checkbox.$defs,
      ...command.$defs,
      ...dialog.$defs,
      ...listbox.$defs,
      ...navigator.$defs,
      ...popover.$defs,
      ...select.$defs,
      ...tabs.$defs,
      ...tagsInput.$defs,
      ...tooltip.$defs,
      ...tree.$defs,

      // Prose: Elements
      ...attribution.$defs,
      ...contentGrid.$defs,
      ...contentSearch.$defs,
      ...navList.$defs,
      ...surround.$defs,
      ...toc.$defs,
      [contentAccordion.key]: contentAccordion.$def,
      [contentFiltersSection.key]: contentFiltersSection.$def,

      // Docula: App-specific elements
      ...community.$defs,
      ...search.$defs,
      ...topbar.$defs,
      ...versionSelect.$defs,
      [container.key]: container.$def,
    },
  },
});
