import { defineNuxtConfig } from "nuxt/config";

import elements from "@foundation/blocks/elements";
import proseElements from "@foundation/prose/elements";

export default defineNuxtConfig({
  compatibilityDate: "2025-11-17",
  extends: ["@foundation/prose"],
  modules: ["nuxt-typed-router"],
  untheme: {
    elements: {
      // Interactive elements
      a: elements.a({
        text: "sys-primary",
        "text-hover": "sys-primary",
        "text-active": "sys-primary-active",
        "text-focus": "sys-primary",
        "text-disabled": "sys-on-surface",
        "background-hover": "ref-color-transparent",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-bold",
        "font-weight-hover": "ref-font-bold",
        "font-weight-active": "ref-font-bold",
        "font-weight-focus": "ref-font-bold",
        "line-height": "ref-leading-normal",
        "text-decoration": "ref-decoration-none",
        "text-decoration-hover": "ref-decoration-underline",
        cursor: "ref-cursor-pointer",
        "cursor-disabled": "ref-cursor-default",
        "box-shadow-focus": "ref-shadow-focus-ring",
      }),
      button: elements.button({
        background: "ref-color-transparent",
        text: "sys-on-surface-variant",
        "text-hover": "sys-on-surface",
        "text-active": "sys-on-surface",
        "background-hover": "sys-hover",
        "background-active": "sys-active",
        cursor: "ref-cursor-pointer",
        "padding-left": "ref-spacing-lg",
        "padding-right": "ref-spacing-lg",
        "padding-top": "ref-spacing-md",
        "padding-bottom": "ref-spacing-md",
        "outline-color": "sys-focus",
        "outline-width": "ref-outline-width-medium",
        "font-weight": "ref-font-bold",
        "font-weight-hover": "ref-font-bold",
        "font-weight-active": "ref-font-bold",
        "font-weight-focus": "ref-font-bold",
        "background-focus": "sys-hover",
        "box-shadow-focus": "ref-shadow-focus-inset",
      }),
      card: elements.card({
        background: "sys-surface",
        "box-shadow": "ref-shadow-md",
      }),
      link: elements.link({
        text: "sys-primary",
        "text-hover": "sys-primary-hover",
        "text-decoration": "ref-none",
      }),
      group: elements.group({
        display: "ref-display-inline-flex",
        "flex-direction": "ref-flex-row",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-start",
        gap: "ref-none",
      }),

      // Accordion
      "accordion-trigger": elements.accordionTrigger({
        background: "ref-color-transparent",
        text: "sys-on-surface-variant",
        cursor: "ref-cursor-pointer",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-bold",
        "text-align": "ref-align-start",
        display: "ref-display-flex",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-between",
        gap: "ref-spacing-xs",
        width: "ref-full",
        "padding-left": "ref-spacing-md",
        "padding-right": "ref-spacing-md",
        "padding-top": "ref-spacing-sm",
        "padding-bottom": "ref-spacing-sm",
        "font-weight-selected": "ref-font-bold",
        "font-weight-hover": "ref-font-bold",
        "font-weight-active": "ref-font-bold",
        "font-weight-focus": "ref-font-bold",
        "font-weight-selected-hover": "ref-font-bold",
        "font-weight-selected-active": "ref-font-bold",
        "font-weight-selected-focus": "ref-font-bold",
        "background-focus": "sys-hover",
        "box-shadow-focus": "ref-shadow-focus-inset",
        "background-selected-focus": "sys-hover",
        "box-shadow-selected-focus": "ref-shadow-focus-inset",
      }),
      "accordion-trigger-content": elements.accordionTriggerContent({
        display: "ref-display-inline-flex",
        "align-items": "ref-align-center",
        gap: "ref-spacing-xs",
      }),
      "accordion-content": elements.accordionContent({
        background: "ref-color-transparent",
        text: "sys-on-surface",
        "font-size": "ref-text-base",
      }),

      // Breadcrumbs
      "breadcrumbs-root": elements.breadcrumbsRoot({}),
      "breadcrumbs-list": elements.breadcrumbsList({
        display: "ref-display-flex",
        "flex-direction": "ref-flex-row",
        "align-items": "ref-align-center",
        gap: "ref-spacing-xs",
        "list-style-type": "ref-list-none",
      }),
      "breadcrumbs-item": elements.breadcrumbsItem({
        display: "ref-display-inline-flex",
        "align-items": "ref-align-center",
        gap: "ref-spacing-xs",
      }),
      "breadcrumbs-link": elements.breadcrumbsLink({
        text: "sys-on-surface-variant",
        "text-hover": "sys-primary",
        "text-active": "sys-primary-active",
        "text-focus": "sys-on-surface",
        "background-hover": "ref-color-transparent",
        "font-size": "ref-text-sm",
        "font-weight": "ref-font-bold",
        "font-weight-hover": "ref-font-bold",
        "font-weight-active": "ref-font-bold",
        "font-weight-focus": "ref-font-bold",
        "text-decoration": "ref-decoration-none",
        "text-decoration-hover": "ref-decoration-underline",
        display: "ref-display-inline-flex",
        "align-items": "ref-align-center",
        gap: "ref-spacing-2xs",
        cursor: "ref-cursor-pointer",
        "box-shadow-focus": "ref-shadow-focus-ring",
      }),
      "breadcrumbs-current": elements.breadcrumbsCurrent({
        text: "sys-primary",
        "font-size": "ref-text-sm",
        "font-weight": "ref-font-bold",
        "text-decoration": "ref-decoration-none",
        display: "ref-display-inline-flex",
        "align-items": "ref-align-center",
        gap: "ref-spacing-2xs",
      }),

      // Layout
      aside: elements.aside({
        display: "ref-display-block",
        top: "ref-position-zero",
        position: "ref-position-sticky",
        background: "sys-surface",
        text: "sys-on-surface",
        "border-color": "ref-color-transparent",
        width: "ref-full",
        height: "ref-full",
      }),
      header: elements.header({
        background: "sys-surface",
        text: "sys-on-surface",
        gap: "ref-spacing-md",
        display: "ref-display-grid",
        "grid-template-columns": "ref-layout-trifold",
        "grid-column": "ref-grid-col-span-all",
        "align-items": "ref-align-center",
        "border-bottom-style": "ref-border-style-solid",
        "border-bottom-width": "ref-border-width-thin",
        "border-color": "sys-outline",
        width: "ref-full",
        "max-width": "ref-width-container",
        "margin-left": "ref-auto",
        "margin-right": "ref-auto",
      }),
      footer: elements.footer({
        background: "sys-surface",
        text: "sys-on-surface",
        gap: "ref-spacing-md",
        display: "ref-display-grid",
        "grid-template-columns": "ref-layout-trifold",
        "grid-column": "ref-grid-col-span-all",
        "align-items": "ref-align-center",
        "border-top-style": "ref-border-style-solid",
        "border-top-width": "ref-border-width-thin",
        "border-color": "sys-outline",
        width: "ref-full",
        "max-width": "ref-width-container",
        "margin-left": "ref-auto",
        "margin-right": "ref-auto",
      }),
      main: elements.main({
        background: "sys-surface",
        text: "sys-on-surface",
        height: "ref-viewport-height",
        "min-height": "ref-viewport-height",
        "max-height": "ref-viewport-height",
        width: "ref-full",
        "max-width": "ref-width-container",
        "margin-left": "ref-auto",
        "margin-right": "ref-auto",
        display: "ref-display-grid",
        "grid-template-rows": "ref-grid-rows-header-content-footer",
      }),
      section: elements.section({
        background: "ref-color-transparent",
        text: "sys-on-surface",
        display: "ref-display-flex",
        "flex-direction": "ref-flex-col",
        gap: "ref-spacing-lg",
        "padding-top": "ref-spacing-lg",
        "padding-right": "ref-spacing-lg",
        "padding-bottom": "ref-spacing-lg",
        "padding-left": "ref-spacing-lg",
      }),
      article: elements.article({
        background: "ref-color-transparent",
        text: "sys-on-surface",
        "max-width": "ref-width-prose",
        "line-height": "ref-leading-relaxed",
        display: "ref-display-block",
      }),
      nav: elements.nav({
        background: "ref-color-transparent",
        text: "sys-on-surface",
      }),

      // Checkbox
      "checkbox-root": elements.checkboxRoot({
        display: "ref-display-inline-flex",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-center",
        width: "ref-spacing-lg",
        height: "ref-spacing-lg",
        background: "sys-surface",
        "background-hover": "sys-hover",
        "background-selected": "sys-primary",
        "background-selected-hover": "sys-primary-hover",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        "border-color-selected": "sys-primary",
        "border-top-left-radius": "ref-radius-sm",
        "border-top-right-radius": "ref-radius-sm",
        "border-bottom-right-radius": "ref-radius-sm",
        "border-bottom-left-radius": "ref-radius-sm",
        cursor: "ref-cursor-pointer",
        "cursor-disabled": "ref-cursor-not-allowed",
        "opacity-disabled": "ref-opacity-50",
        "transition-duration": "ref-duration-fast",
        "transition-easing": "ref-ease-out",
      }),
      "checkbox-indicator": elements.checkboxIndicator({
        display: "ref-display-flex",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-center",
        text: "sys-on-primary",
        "font-size": "ref-text-sm",
      }),

      // Avatar
      "avatar-root": elements.avatarRoot({
        width: "ref-spacing-2xl",
        height: "ref-spacing-2xl",
        "border-top-left-radius": "ref-radius-full",
        "border-top-right-radius": "ref-radius-full",
        "border-bottom-right-radius": "ref-radius-full",
        "border-bottom-left-radius": "ref-radius-full",
        "overflow-x": "ref-overflow-hidden",
        "overflow-y": "ref-overflow-hidden",
        display: "ref-display-inline-flex",
      }),
      "avatar-image": elements.avatarImage({
        width: "ref-full",
        height: "ref-full",
        "object-fit": "ref-object-cover",
        display: "ref-display-block",
      }),
      "avatar-fallback": elements.avatarFallback({
        width: "ref-full",
        height: "ref-full",
        background: "sys-surface-container",
        text: "sys-on-surface",
        display: "ref-display-inline-flex",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-center",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-medium",
      }),

      // Input
      input: elements.input({
        background: "sys-surface",
        text: "sys-on-surface",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-normal",
        "padding-top": "ref-spacing-sm",
        "padding-right": "ref-spacing-md",
        "padding-bottom": "ref-spacing-sm",
        "padding-left": "ref-spacing-md",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        width: "ref-full",
      }),

      // Label
      label: elements.label({
        text: "sys-on-surface",
        "font-size": "ref-text-sm",
        "font-weight": "ref-font-medium",
        display: "ref-display-block",
      }),

      // Icon
      icon: elements.icon({
        text: "ref-color-current",
        opacity: "ref-opacity-100",
        display: "ref-display-inline-flex",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-center",
        width: "ref-width-1em",
        height: "ref-height-1em",
      }),

      // Img
      img: elements.img({
        display: "ref-display-block",
        "max-width": "ref-full",
        height: "ref-auto",
        "margin-top": "ref-spacing-lg",
        "margin-bottom": "ref-spacing-lg",
      }),

      // Select
      "select-root": elements.selectRoot({
        background: "ref-color-transparent",
      }),
      "select-trigger": elements.selectTrigger({
        display: "ref-display-flex",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-between",
        gap: "ref-spacing-xs",
        background: "sys-surface",
        text: "sys-on-surface",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-normal",
        "padding-top": "ref-spacing-sm",
        "padding-right": "ref-spacing-md",
        "padding-bottom": "ref-spacing-sm",
        "padding-left": "ref-spacing-md",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        "border-color-hover": "sys-outline",
        "border-color-focus": "sys-primary",
        "background-hover": "sys-hover",
        "background-focus": "sys-surface",
        "box-shadow-focus": "ref-shadow-focus-ring",
        cursor: "ref-cursor-pointer",
        width: "ref-full",
        "transition-duration": "ref-duration-fast",
        "transition-easing": "ref-ease-out",
      }),
      "select-content": elements.selectContent({
        background: "sys-surface-container",
        text: "sys-on-surface",
        "padding-top": "ref-spacing-xs",
        "padding-right": "ref-spacing-xs",
        "padding-bottom": "ref-spacing-xs",
        "padding-left": "ref-spacing-xs",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        "z-index": "ref-z-dropdown",
        "max-height": "ref-width-md",
        "overflow-y": "ref-overflow-auto",
      }),
      "select-item": elements.selectItem({
        background: "ref-color-transparent",
        text: "sys-on-surface",
        "text-hover": "sys-on-surface",
        "text-selected": "sys-primary",
        "text-selected-hover": "sys-primary",
        "background-hover": "sys-hover",
        "background-selected": "sys-surface-container-high",
        "background-selected-hover": "sys-hover",
        "padding-top": "ref-spacing-xs",
        "padding-right": "ref-spacing-md",
        "padding-bottom": "ref-spacing-xs",
        "padding-left": "ref-spacing-md",
        cursor: "ref-cursor-pointer",
        "font-size": "ref-text-base",
        "background-focus": "sys-hover",
        "box-shadow-focus": "ref-shadow-focus-inset",
        "background-selected-focus": "sys-hover",
        "transition-duration": "ref-duration-fast",
        "transition-easing": "ref-ease-out",
      }),

      // Tags Input
      "tags-input-root": elements.tagsInputRoot({
        display: "ref-display-flex",
        "flex-direction": "ref-flex-row",
        "flex-wrap": "ref-layout-cluster",
        "align-items": "ref-align-center",
        gap: "ref-spacing-xs",
        background: "sys-surface",
        text: "sys-on-surface",
        "padding-top": "ref-spacing-sm",
        "padding-right": "ref-spacing-md",
        "padding-bottom": "ref-spacing-sm",
        "padding-left": "ref-spacing-md",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        "border-radius": "ref-radius-md",
      }),
      "tags-input-item": elements.tagsInputItem({
        display: "ref-display-inline-flex",
        "align-items": "ref-align-center",
        gap: "ref-spacing-2xs",
        background: "sys-surface-container-high",
        text: "sys-on-surface",
        "font-size": "ref-text-sm",
        "font-weight": "ref-font-medium",
        "white-space": "ref-whitespace-nowrap",
        "padding-left": "ref-spacing-sm",
        "padding-right": "ref-spacing-sm",
        "padding-top": "ref-spacing-2xs",
        "padding-bottom": "ref-spacing-2xs",
        "transition-duration": "ref-duration-fast",
        "transition-easing": "ref-ease-out",
      }),
      "tags-input-item-text": elements.tagsInputItemText({
        "font-size": "ref-text-sm",
      }),
      "tags-input-item-delete": elements.tagsInputItemDelete({
        display: "ref-display-inline-flex",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-center",
        background: "ref-color-transparent",
        "background-hover": "sys-hover",
        text: "sys-on-surface-variant",
        "text-hover": "sys-on-surface",
        cursor: "ref-cursor-pointer",
        "border-radius": "ref-radius-sm",
        "transition-duration": "ref-duration-fast",
        "transition-easing": "ref-ease-out",
      }),
      "tags-input-input": elements.tagsInputInput({
        background: "ref-color-transparent",
        text: "sys-on-surface",
        "font-size": "ref-text-base",
        "flex-grow": "ref-flex-1",
        "min-width": "ref-width-xs",
      }),

      // Listbox
      "listbox-root": elements.listboxRoot({
        background: "ref-color-transparent",
      }),
      "listbox-content": elements.listboxContent({
        background: "ref-color-transparent",
        display: "ref-display-flex",
        "flex-direction": "ref-flex-col",
        gap: "ref-spacing-none",
      }),
      "listbox-item": elements.listboxItem({
        background: "ref-color-transparent",
        text: "sys-on-surface-variant",
        "text-hover": "sys-on-surface",
        "text-active": "sys-primary",
        "text-selected": "sys-primary",
        "text-selected-hover": "sys-primary",
        "background-hover": "sys-hover",
        "background-selected": "sys-surface-container-high",
        "background-selected-hover": "sys-hover",
        "box-shadow-selected": "ref-shadow-border-left",
        "box-shadow-selected-hover": "ref-shadow-border-left",
        "box-shadow-selected-active": "ref-shadow-border-left",
        "border-color": "ref-color-transparent",
        "padding-left": "ref-spacing-md",
        "padding-right": "ref-spacing-md",
        "padding-top": "ref-spacing-xs",
        "padding-bottom": "ref-spacing-xs",
        cursor: "ref-cursor-pointer",
        "cursor-disabled": "ref-cursor-not-allowed",
        "font-size": "ref-text-base",
        "text-selected-active": "sys-primary",
        "text-selected-focus": "sys-primary",
        display: "ref-display-flex",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-between",
        gap: "ref-spacing-sm",
        "background-focus": "sys-hover",
        "box-shadow-focus": "ref-shadow-focus-inset",
        "background-selected-focus": "sys-hover",
        "box-shadow-selected-focus": "ref-shadow-border-left-focus",
      }),

      // Caption
      caption: elements.caption({
        background: "ref-color-transparent",
        text: "sys-on-surface-variant",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-bold",
        display: "ref-display-flex",
        "align-items": "ref-align-center",
        gap: "ref-spacing-xs",
        "padding-left": "ref-spacing-md",
        "padding-right": "ref-spacing-md",
        "padding-top": "ref-spacing-sm",
        "padding-bottom": "ref-spacing-sm",
      }),

      // Chip
      chip: elements.chip({
        background: "sys-surface-container-high",
        text: "sys-on-surface",
        "font-size": "ref-text-sm",
        "font-weight": "ref-font-medium",
        "white-space": "ref-whitespace-nowrap",
        display: "ref-display-inline-flex",
        "align-items": "ref-align-center",
        gap: "ref-spacing-2xs",
        "padding-left": "ref-spacing-sm",
        "padding-right": "ref-spacing-sm",
        "padding-top": "ref-spacing-2xs",
        "padding-bottom": "ref-spacing-2xs",
      }),

      // Table of Contents
      "toc-root": proseElements.tocRoot({
        background: "ref-color-transparent",
      }),
      "toc-content": proseElements.tocContent({
        background: "ref-color-transparent",
        display: "ref-display-flex",
        "flex-direction": "ref-flex-col",
        gap: "ref-spacing-none",
      }),
      "toc-item": proseElements.tocItem({
        background: "ref-color-transparent",
        text: "sys-on-surface-variant",
        "text-hover": "sys-on-surface",
        "text-active": "sys-primary",
        "text-selected": "sys-primary",
        "text-selected-hover": "sys-primary",
        "background-hover": "sys-hover",
        "background-selected": "sys-surface-container-high",
        "background-selected-hover": "sys-hover",
        "box-shadow-selected": "ref-shadow-border-left",
        "box-shadow-selected-hover": "ref-shadow-border-left",
        "box-shadow-selected-active": "ref-shadow-border-left",
        "border-color": "ref-color-transparent",
        "padding-left": "ref-spacing-md",
        "padding-right": "ref-spacing-md",
        "padding-top": "ref-spacing-xs",
        "padding-bottom": "ref-spacing-xs",
        cursor: "ref-cursor-pointer",
        "font-size": "ref-text-base",
        "text-selected-active": "sys-primary",
        "text-selected-focus": "sys-primary",
        display: "ref-display-flex",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-between",
        gap: "ref-spacing-sm",
        "background-focus": "sys-hover",
        "box-shadow-focus": "ref-shadow-focus-inset",
        "background-selected-focus": "sys-hover",
        "box-shadow-selected-focus": "ref-shadow-border-left-focus",
      }),

      // Content Grid
      "content-grid": proseElements.contentGrid({
        display: "ref-display-grid",
        "grid-template-columns": "ref-layout-grid-3",
        gap: "ref-spacing-none",
      }),
      "content-grid-item": proseElements.contentGridItem({
        display: "ref-display-flex",
        "flex-direction": "ref-flex-col",
        "align-items": "ref-align-start",
        "justify-content": "ref-justify-start",
        gap: "ref-spacing-xs",
        "padding-top": "ref-spacing-md",
        "padding-right": "ref-spacing-lg",
        "padding-bottom": "ref-spacing-md",
        "padding-left": "ref-spacing-lg",
        "text-decoration": "ref-decoration-none",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        "border-color": "ref-color-transparent",
        "border-color-hover": "sys-outline",
        "border-color-active": "sys-outline",
        "border-color-focus": "sys-outline",
        "background-hover": "sys-hover",
        "background-focus": "sys-hover",
        "box-shadow-focus": "ref-shadow-focus-inset",
        cursor: "ref-cursor-pointer",
        "transition-duration": "ref-duration-fast",
        "transition-easing": "ref-ease-out",
      }),
      "content-grid-title": proseElements.contentGridTitle({
        text: "sys-on-surface",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-bold",
      }),
      "content-grid-description": proseElements.contentGridDescription({
        text: "sys-on-surface-variant",
        "font-size": "ref-text-sm",
        "font-weight": "ref-font-normal",
      }),
      "content-grid-meta": proseElements.contentGridMeta({
        display: "ref-display-flex",
        "flex-direction": "ref-flex-row",
        gap: "ref-spacing-sm",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-between",
        width: "ref-full",
      }),
      "content-grid-author": proseElements.contentGridAuthor({
        display: "ref-display-inline-flex",
        "align-items": "ref-align-center",
        gap: "ref-spacing-2xs",
        text: "sys-on-surface-variant",
        "font-size": "ref-text-xs",
        "font-weight": "ref-font-normal",
        "white-space": "ref-whitespace-nowrap",
      }),
      "content-grid-published": proseElements.contentGridPublished({
        display: "ref-display-inline-flex",
        "align-items": "ref-align-center",
        gap: "ref-spacing-2xs",
        text: "sys-on-surface-variant",
        "font-size": "ref-text-xs",
        "font-weight": "ref-font-normal",
        "white-space": "ref-whitespace-nowrap",
      }),

      // Attribution
      "attribution-root": proseElements.attributionRoot({
        display: "ref-display-flex",
        "flex-direction": "ref-flex-col",
        gap: "ref-spacing-md",
        "max-width": "ref-width-prose",
        "border-top-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        "padding-top": "ref-spacing-lg",
        "padding-bottom": "ref-spacing-lg",
      }),
      "attribution-container": proseElements.attributionContainer({
        display: "ref-display-flex",
        "flex-direction": "ref-flex-row",
        "justify-content": "ref-justify-between",
        "align-items": "ref-align-start",
        gap: "ref-spacing-md",
      }),
      "attribution-meta": proseElements.attributionMeta({
        display: "ref-display-grid",
        "grid-template-columns": "ref-layout-sidebar-left",
        "align-items": "ref-align-center",
        gap: "ref-spacing-xs",
      }),
      "attribution-author": proseElements.attributionAuthor({
        text: "sys-on-surface",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-bold",
        "white-space": "ref-whitespace-nowrap",
      }),
      "attribution-published": proseElements.attributionPublished({
        text: "sys-on-surface-variant",
        "font-size": "ref-text-sm",
        "font-weight": "ref-font-normal",
        "white-space": "ref-whitespace-nowrap",
      }),
      "attribution-tags": proseElements.attributionTags({
        display: "ref-display-flex",
        "flex-direction": "ref-flex-row",
        "flex-wrap": "ref-flex-wrap",
        gap: "ref-spacing-xs",
      }),

      // Surround (Prev/Next)
      "surround-root": proseElements.surroundRoot({
        display: "ref-display-flex",
        "flex-direction": "ref-flex-row",
        width: "ref-full",
        "max-width": "ref-width-prose",
        gap: "ref-spacing-md",
      }),
      "surround-prev": proseElements.surroundPrev({
        display: "ref-display-flex",
        "flex-direction": "ref-flex-col",
        "align-items": "ref-align-start",
        "justify-content": "ref-justify-center",
        "flex-grow": "ref-flex-grow",
        "flex-basis": "ref-flex-basis-half",
        gap: "ref-spacing-xs",
        "padding-top": "ref-spacing-md",
        "padding-right": "ref-spacing-lg",
        "padding-bottom": "ref-spacing-md",
        "padding-left": "ref-spacing-lg",
        "text-decoration": "ref-decoration-none",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        "border-color-hover": "sys-outline",
        "border-color-active": "sys-outline",
        "border-color-focus": "sys-outline",
        "background-hover": "sys-hover",
        "background-focus": "sys-hover",
        "box-shadow-focus": "ref-shadow-focus-inset",
        cursor: "ref-cursor-pointer",
        "transition-duration": "ref-duration-fast",
        "transition-easing": "ref-ease-out",
      }),
      "surround-next": proseElements.surroundNext({
        display: "ref-display-flex",
        "flex-direction": "ref-flex-col",
        "align-items": "ref-align-end",
        "justify-content": "ref-justify-center",
        "flex-grow": "ref-flex-grow",
        "flex-basis": "ref-flex-basis-half",
        gap: "ref-spacing-xs",
        "padding-top": "ref-spacing-md",
        "padding-right": "ref-spacing-lg",
        "padding-bottom": "ref-spacing-md",
        "padding-left": "ref-spacing-lg",
        "text-decoration": "ref-decoration-none",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        "border-color-hover": "sys-outline",
        "border-color-active": "sys-outline",
        "border-color-focus": "sys-outline",
        "background-hover": "sys-hover",
        "background-focus": "sys-hover",
        "box-shadow-focus": "ref-shadow-focus-inset",
        cursor: "ref-cursor-pointer",
        "transition-duration": "ref-duration-fast",
        "transition-easing": "ref-ease-out",
      }),
      "surround-label": proseElements.surroundLabel({
        display: "ref-display-inline-flex",
        "align-items": "ref-align-center",
        gap: "ref-spacing-2xs",
        text: "sys-on-surface-variant",
        "font-size": "ref-text-sm",
        "font-weight": "ref-font-medium",
      }),
      "surround-title": proseElements.surroundTitle({
        text: "sys-on-surface",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-bold",
      }),
      "surround-prev-description": proseElements.surroundPrevDescription({
        text: "sys-on-surface-variant",
        "font-size": "ref-text-sm",
        "font-weight": "ref-font-normal",
      }),
      "surround-next-description": proseElements.surroundNextDescription({
        text: "sys-on-surface-variant",
        "font-size": "ref-text-sm",
        "font-weight": "ref-font-normal",
        "text-align": "ref-text-align-end",
      }),

      // Tree
      "tree-root": elements.treeRoot({
        display: "ref-display-flex",
        "flex-direction": "ref-flex-col",
      }),
      "tree-branch": elements.treeBranch({
        display: "ref-display-flex",
        "flex-direction": "ref-flex-col",
        background: "ref-color-transparent",
        text: "sys-on-surface-variant",
        "text-hover": "sys-on-surface",
        "text-open": "sys-on-surface",
        "text-open-hover": "sys-on-surface",
        "background-hover": "sys-hover",
        cursor: "ref-cursor-pointer",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-bold",
        "font-weight-hover": "ref-font-bold",
        "font-weight-active": "ref-font-bold",
        "font-weight-focus": "ref-font-bold",
        "font-weight-open": "ref-font-bold",
        "font-weight-open-hover": "ref-font-bold",
        "font-weight-open-active": "ref-font-bold",
        "font-weight-open-focus": "ref-font-bold",
        "background-focus": "sys-hover",
        "box-shadow-focus": "ref-shadow-focus-inset",
        "background-open-focus": "sys-hover",
        "box-shadow-open-focus": "ref-shadow-focus-inset",
      }),
      "tree-branch-content": elements.treeBranchContent({
        display: "ref-display-flex",
        "flex-direction": "ref-flex-row",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-between",
        gap: "ref-spacing-xs",
        "padding-left": "ref-spacing-md",
        "padding-right": "ref-spacing-md",
        "padding-top": "ref-spacing-xs",
        "padding-bottom": "ref-spacing-xs",
      }),
      "tree-leaf": elements.treeLeaf({
        background: "ref-color-transparent",
        text: "sys-on-surface-variant",
        "text-hover": "sys-on-surface",
        "text-active": "sys-primary",
        "text-selected": "sys-primary",
        "text-selected-hover": "sys-primary",
        "background-hover": "sys-hover",
        "background-selected": "sys-surface-container-high",
        "background-selected-hover": "sys-hover",
        "box-shadow-selected": "ref-shadow-border-left",
        "box-shadow-selected-hover": "ref-shadow-border-left",
        "box-shadow-selected-active": "ref-shadow-border-left",
        "border-color": "ref-color-transparent",
        cursor: "ref-cursor-pointer",
        "font-size": "ref-text-base",
        "text-selected-active": "sys-primary",
        "text-selected-focus": "sys-primary",
        display: "ref-display-flex",
        "flex-direction": "ref-flex-col",
        "background-focus": "sys-hover",
        "box-shadow-focus": "ref-shadow-focus-inset",
        "background-selected-focus": "sys-hover",
        "box-shadow-selected-focus": "ref-shadow-border-left-focus",
      }),
      "tree-leaf-content": elements.treeLeafContent({
        display: "ref-display-flex",
        "flex-direction": "ref-flex-row",
        "align-items": "ref-align-center",
        gap: "ref-spacing-xs",
        "padding-left": "ref-spacing-md",
        "padding-right": "ref-spacing-md",
        "padding-top": "ref-spacing-xs",
        "padding-bottom": "ref-spacing-xs",
        // Link style resets
        text: "ref-color-inherit",
        "text-decoration": "ref-decoration-none",
        "font-weight": "ref-font-normal",
      }),

      // Tabs
      "tabs-root": elements.tabsRoot({
        background: "ref-color-transparent",
      }),
      "tabs-list": elements.tabsList({
        background: "ref-color-transparent",
        display: "ref-display-flex",
        "flex-direction": "ref-flex-row",
        gap: "ref-spacing-none",
        "border-bottom-width": "ref-border-width-thin",
        "border-bottom-style": "ref-border-style-solid",
        "border-color": "sys-outline",
      }),
      "tabs-trigger": elements.tabsTrigger({
        background: "ref-color-transparent",
        text: "sys-on-surface-variant",
        "text-hover": "sys-on-surface",
        "text-active": "sys-primary",
        "text-selected": "sys-primary",
        "text-selected-hover": "sys-primary",
        "text-selected-active": "sys-primary",
        "text-selected-focus": "sys-primary",
        "background-selected": "sys-surface-container-high",
        "border-bottom-width": "ref-hairline",
        "box-shadow-selected": "ref-shadow-border-bottom",
        "box-shadow-selected-hover": "ref-shadow-border-bottom",
        "box-shadow-selected-active": "ref-shadow-border-bottom",
        cursor: "ref-cursor-pointer",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-bold",
        "font-weight-hover": "ref-font-bold",
        "font-weight-active": "ref-font-bold",
        "font-weight-focus": "ref-font-bold",
        "font-weight-selected": "ref-font-bold",
        "font-weight-selected-hover": "ref-font-bold",
        "font-weight-selected-active": "ref-font-bold",
        "font-weight-selected-focus": "ref-font-bold",
        "padding-left": "ref-spacing-lg",
        "padding-right": "ref-spacing-lg",
        "padding-top": "ref-spacing-md",
        "padding-bottom": "ref-spacing-md",
        display: "ref-display-flex",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-center",
        gap: "ref-spacing-md",
        "background-focus": "sys-hover",
        "box-shadow-focus": "ref-shadow-focus-inset",
        "background-selected-focus": "sys-hover",
        "box-shadow-selected-focus": "ref-shadow-border-bottom-focus",
      }),
      "tabs-content": elements.tabsContent({
        background: "ref-color-transparent",
        text: "sys-on-surface",
        "font-size": "ref-text-base",
      }),

      // Table
      table: elements.table({
        display: "ref-display-table",
        width: "ref-full",
        "border-collapse": "ref-border-collapse",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        "margin-top": "ref-spacing-lg",
        "margin-bottom": "ref-spacing-lg",
      }),
      thead: elements.thead({
        display: "ref-display-table-header-group",
        background: "sys-surface-container-high",
      }),
      tbody: elements.tbody({
        display: "ref-display-table-row-group",
      }),
      tr: elements.tr({
        display: "ref-display-table-row",
        "border-bottom-width": "ref-border-width-thin",
        "border-bottom-style": "ref-border-style-solid",
        "border-color": "sys-outline",
      }),
      th: elements.th({
        display: "ref-display-table-cell",
        text: "sys-on-surface",
        "font-weight": "ref-font-bold",
        "font-size": "ref-text-sm",
        "padding-top": "ref-spacing-sm",
        "padding-right": "ref-spacing-md",
        "padding-bottom": "ref-spacing-sm",
        "padding-left": "ref-spacing-md",
        "text-align": "ref-align-start",
        "border-bottom-width": "ref-border-width-thin",
        "border-bottom-style": "ref-border-style-solid",
        "border-color": "sys-outline",
      }),
      td: elements.td({
        display: "ref-display-table-cell",
        text: "sys-on-surface",
        "font-size": "ref-text-sm",
        "padding-top": "ref-spacing-sm",
        "padding-right": "ref-spacing-md",
        "padding-bottom": "ref-spacing-sm",
        "padding-left": "ref-spacing-md",
        "border-bottom-width": "ref-border-width-thin",
        "border-bottom-style": "ref-border-style-solid",
        "border-color": "sys-outline",
      }),

      // Tooltip
      "tooltip-content": elements.tooltipContent({
        background: "sys-surface-container",
        text: "sys-on-surface",
        "font-size": "ref-text-sm",
        "padding-left": "ref-spacing-xs",
        "padding-right": "ref-spacing-xs",
        "padding-top": "ref-spacing-xs",
        "padding-bottom": "ref-spacing-xs",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        "z-index": "ref-z-tooltip",
        display: "ref-display-inline-flex",
        "align-items": "ref-align-center",
        gap: "ref-spacing-xs",
      }),

      // Navigator
      "navigator-root": elements.navigatorRoot({
        display: "ref-display-flex",
        "align-items": "ref-align-center",
        position: "ref-position-relative",
      }),
      "navigator-list": elements.navigatorList({
        display: "ref-display-flex",
        "flex-direction": "ref-flex-row",
        "align-items": "ref-align-center",
        gap: "ref-spacing-none",
      }),
      "navigator-item": elements.navigatorItem({
        display: "ref-display-flex",
      }),
      "navigator-trigger": elements.navigatorTrigger({
        background: "ref-color-transparent",
        text: "sys-on-surface-variant",
        "text-hover": "sys-on-surface",
        "text-active": "sys-on-surface",
        "text-open": "sys-on-surface",
        "text-open-hover": "sys-on-surface",
        "text-open-active": "sys-on-surface",
        "background-open": "sys-surface-container-high",
        "background-hover": "sys-hover",
        "background-open-hover": "sys-hover",
        cursor: "ref-cursor-pointer",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-bold",
        "font-weight-hover": "ref-font-bold",
        "font-weight-active": "ref-font-bold",
        "font-weight-focus": "ref-font-bold",
        "font-weight-open": "ref-font-bold",
        "font-weight-open-hover": "ref-font-bold",
        "font-weight-open-active": "ref-font-bold",
        "font-weight-open-focus": "ref-font-bold",
        "padding-left": "ref-spacing-lg",
        "padding-right": "ref-spacing-lg",
        "padding-top": "ref-spacing-md",
        "padding-bottom": "ref-spacing-md",
        display: "ref-display-flex",
        "align-items": "ref-align-center",
        "justify-content": "ref-justify-center",
        gap: "ref-spacing-xs",
        "background-focus": "sys-hover",
        "box-shadow-focus": "ref-shadow-focus-inset",
        "background-open-focus": "sys-hover",
        "box-shadow-open-focus": "ref-shadow-focus-inset",
      }),
      "navigator-link": elements.navigatorLink({
        background: "ref-color-transparent",
        text: "sys-on-surface-variant",
        "text-hover": "sys-on-surface",
        "text-active": "sys-on-surface",
        "text-focus": "sys-on-surface",
        "background-hover": "sys-hover",
        cursor: "ref-cursor-pointer",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-bold",
        "font-weight-hover": "ref-font-bold",
        "font-weight-active": "ref-font-bold",
        "font-weight-focus": "ref-font-bold",
        "padding-left": "ref-spacing-lg",
        "padding-right": "ref-spacing-lg",
        "padding-top": "ref-spacing-md",
        "padding-bottom": "ref-spacing-md",
        display: "ref-display-flex",
        "align-items": "ref-align-center",
        gap: "ref-spacing-xs",
        "text-decoration": "ref-decoration-none",
        "background-focus": "sys-hover",
        "box-shadow-focus": "ref-shadow-focus-inset",
      }),
      "navigator-content": elements.navigatorContent({
        background: "sys-surface-container",
        text: "sys-on-surface",
        "padding-top": "ref-spacing-sm",
        "padding-right": "ref-spacing-sm",
        "padding-bottom": "ref-spacing-sm",
        "padding-left": "ref-spacing-sm",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        display: "ref-display-flex",
        "flex-direction": "ref-flex-col",
        gap: "ref-spacing-none",
        width: "ref-max",
      }),
      "navigator-viewport": elements.navigatorViewport({
        position: "ref-position-absolute",
        top: "ref-position-zero",
        "overflow-x": "ref-overflow-hidden",
        "overflow-y": "ref-overflow-hidden",
      }),
      "navigator-viewport-wrapper": elements.navigatorViewportWrapper({
        position: "ref-position-absolute",
        top: "ref-position-full-gap-sm",
        left: "ref-position-zero",
        "z-index": "ref-z-dropdown",
        display: "ref-display-flex",
        "justify-content": "ref-justify-start",
        width: "ref-full",
      }),
      "navigator-indicator": elements.navigatorIndicator({
        background: "sys-primary",
        height: "ref-hairline",
        position: "ref-position-absolute",
        bottom: "ref-position-zero",
        "z-index": "ref-z-base",
      }),
      "navigator-grid": elements.navigatorGrid({
        display: "ref-display-grid",
        "grid-template-columns": "ref-layout-sidebar",
        "grid-template-rows": "ref-layout-bifold",
        gap: "ref-spacing-sm",
      }),
      "navigator-card": elements.navigatorCard({
        background: "sys-surface-container",
        text: "sys-on-surface-variant",
        "text-hover": "sys-on-surface",
        "text-active": "sys-on-surface",
        "text-focus": "sys-on-surface",
        "background-hover": "sys-surface-container-high",
        cursor: "ref-cursor-pointer",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-bold",
        "font-weight-hover": "ref-font-bold",
        "font-weight-active": "ref-font-bold",
        "font-weight-focus": "ref-font-bold",
        "padding-left": "ref-spacing-md",
        "padding-right": "ref-spacing-md",
        "padding-top": "ref-spacing-md",
        "padding-bottom": "ref-spacing-md",
        display: "ref-display-flex",
        "flex-direction": "ref-flex-col",
        "align-items": "ref-align-start",
        "justify-content": "ref-justify-start",
        gap: "ref-spacing-xs",
        "text-decoration": "ref-decoration-none",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        "background-focus": "sys-surface-container-high",
        "box-shadow-focus": "ref-shadow-focus-inset",
        "transition-duration": "ref-duration-fast",
        "transition-easing": "ref-ease-out",
      }),
      "navigator-featured": elements.navigatorFeatured({
        background: "sys-surface-container-high",
        text: "sys-on-surface-variant",
        "text-hover": "sys-on-surface",
        "text-active": "sys-on-surface",
        "text-focus": "sys-on-surface",
        "background-hover": "sys-surface-container-highest",
        cursor: "ref-cursor-pointer",
        "font-size": "ref-text-lg",
        "font-weight": "ref-font-bold",
        "font-weight-hover": "ref-font-bold",
        "font-weight-active": "ref-font-bold",
        "font-weight-focus": "ref-font-bold",
        "padding-left": "ref-spacing-lg",
        "padding-right": "ref-spacing-lg",
        "padding-top": "ref-spacing-lg",
        "padding-bottom": "ref-spacing-lg",
        display: "ref-display-flex",
        "flex-direction": "ref-flex-col",
        "align-items": "ref-align-start",
        "justify-content": "ref-justify-start",
        gap: "ref-spacing-sm",
        "text-decoration": "ref-decoration-none",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        "grid-row": "ref-grid-row-span-all",
        "background-focus": "sys-surface-container-highest",
        "box-shadow-focus": "ref-shadow-focus-inset",
        "transition-duration": "ref-duration-fast",
        "transition-easing": "ref-ease-out",
      }),

      // Dialog
      "dialog-overlay": elements.dialogOverlay({
        background: "sys-surface",
        opacity: "ref-opacity-50",
        position: "ref-position-fixed",
        top: "ref-position-zero",
        left: "ref-position-zero",
        right: "ref-position-zero",
        bottom: "ref-position-zero",
        "z-index": "ref-z-overlay",
      }),
      "dialog-content": elements.dialogContent({
        background: "sys-surface-container",
        text: "sys-on-surface",
        position: "ref-position-fixed",
        top: "ref-position-half",
        left: "ref-position-half",
        transform: "ref-transform-center",
        "padding-top": "ref-spacing-xl",
        "padding-right": "ref-spacing-xl",
        "padding-bottom": "ref-spacing-xl",
        "padding-left": "ref-spacing-xl",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        "z-index": "ref-z-modal",
      }),

      // Typography
      p: elements.p({
        text: "sys-on-surface",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-normal",
        "line-height": "ref-leading-normal",
        display: "ref-display-block",
        "margin-top": "ref-spacing-base",
        "margin-bottom": "ref-spacing-base",
      }),
      h1: elements.h1({
        text: "sys-on-surface",
        "font-size": "ref-text-4xl",
        "font-weight": "ref-font-bold",
        "line-height": "ref-leading-tighter",
        display: "ref-display-block",
        "margin-top": "ref-spacing-none",
        "margin-bottom": "ref-spacing-xl",
      }),
      h2: elements.h2({
        text: "sys-on-surface",
        "font-size": "ref-text-2xl",
        "font-weight": "ref-font-bold",
        "line-height": "ref-leading-snug",
        display: "ref-display-block",
        "margin-top": "ref-spacing-2xl",
        "margin-bottom": "ref-spacing-lg",
        "scroll-margin-top": "ref-scroll-lg",
      }),
      h3: elements.h3({
        text: "sys-on-surface",
        "font-size": "ref-text-xl",
        "font-weight": "ref-font-semibold",
        "line-height": "ref-leading-cozy",
        display: "ref-display-block",
        "margin-top": "ref-spacing-xl",
        "margin-bottom": "ref-spacing-sm",
        "scroll-margin-top": "ref-scroll-lg",
      }),
      h4: elements.h4({
        text: "sys-on-surface",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-semibold",
        "line-height": "ref-leading-normal",
        display: "ref-display-block",
        "margin-top": "ref-spacing-lg",
        "margin-bottom": "ref-spacing-xs",
        "scroll-margin-top": "ref-scroll-lg",
      }),
      h5: elements.h5({
        text: "sys-on-surface-variant",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-semibold",
        "line-height": "ref-leading-normal",
        display: "ref-display-block",
        "margin-top": "ref-spacing-lg",
        "margin-bottom": "ref-spacing-xs",
        "scroll-margin-top": "ref-scroll-lg",
      }),
      h6: elements.h6({
        text: "sys-on-surface-variant",
        "font-size": "ref-text-base",
        "font-weight": "ref-font-medium",
        "line-height": "ref-leading-normal",
        display: "ref-display-block",
        "margin-top": "ref-spacing-lg",
        "margin-bottom": "ref-spacing-xs",
        "scroll-margin-top": "ref-scroll-lg",
      }),
      code: elements.code({
        text: "sys-on-surface",
        background: "sys-surface-container",
        "font-family": "ref-font-mono",
        "font-size": "ref-text-sm",
        "padding-top": "ref-spacing-2xs",
        "padding-right": "ref-spacing-xs",
        "padding-bottom": "ref-spacing-2xs",
        "padding-left": "ref-spacing-xs",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        display: "ref-display-inline-block",
      }),
      kbd: elements.kbd({
        text: "sys-on-surface",
        background: "sys-surface-container-high",
        "font-family": "ref-font-mono",
        "font-size": "ref-text-xs",
        "font-weight": "ref-font-semibold",
        "padding-top": "ref-spacing-2xs",
        "padding-right": "ref-spacing-2xs",
        "padding-bottom": "ref-spacing-2xs",
        "padding-left": "ref-spacing-2xs",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        display: "ref-display-inline-flex",
        "align-items": "ref-align-center",
        gap: "ref-spacing-2xs",
      }),
      pre: elements.pre({
        text: "sys-on-surface",
        background: "sys-surface-container",
        "font-family": "ref-font-mono",
        "font-size": "ref-text-sm",
        "padding-top": "ref-spacing-md",
        "padding-right": "ref-spacing-md",
        "padding-bottom": "ref-spacing-md",
        "padding-left": "ref-spacing-md",
        "border-top-width": "ref-border-width-thin",
        "border-right-width": "ref-border-width-thin",
        "border-bottom-width": "ref-border-width-thin",
        "border-left-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-right-style": "ref-border-style-solid",
        "border-bottom-style": "ref-border-style-solid",
        "border-left-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        display: "ref-display-block",
        "overflow-x": "ref-overflow-auto",
        "margin-top": "ref-spacing-base",
        "margin-bottom": "ref-spacing-base",
      }),
      strong: elements.strong({
        "font-weight": "ref-font-bold",
        display: "ref-display-inline",
      }),
      em: elements.em({
        "font-style": "ref-font-italic",
        display: "ref-display-inline",
      }),
      del: elements.del({
        "text-decoration": "ref-decoration-line-through",
        display: "ref-display-inline",
      }),
      blockquote: elements.blockquote({
        text: "sys-on-surface-variant",
        "font-style": "ref-font-italic",
        "border-left-width": "ref-border-width-thick",
        "border-left-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        "padding-left": "ref-spacing-lg",
        "margin-top": "ref-spacing-xl",
        "margin-bottom": "ref-spacing-xl",
        display: "ref-display-block",
      }),
      hr: elements.hr({
        "border-top-width": "ref-border-width-thin",
        "border-top-style": "ref-border-style-solid",
        "border-color": "sys-outline",
        "margin-top": "ref-spacing-2xl",
        "margin-bottom": "ref-spacing-2xl",
        display: "ref-display-block",
      }),
      ul: elements.ul({
        "list-style-type": "ref-list-disc",
        "padding-left": "ref-spacing-xl",
        "margin-top": "ref-spacing-base",
        "margin-bottom": "ref-spacing-base",
        display: "ref-display-block",
      }),
      ol: elements.ol({
        "list-style-type": "ref-list-decimal",
        "padding-left": "ref-spacing-xl",
        "margin-top": "ref-spacing-base",
        "margin-bottom": "ref-spacing-base",
        display: "ref-display-block",
      }),
      li: elements.li({
        display: "ref-display-list-item",
        "margin-top": "ref-spacing-xs",
        "margin-bottom": "ref-spacing-xs",
      }),
    },
  },
});
