import { button } from "@foundation/blocks/elements";
import { createTokenDef } from "./helpers";

export default [
  createTokenDef(button.key, {
    display: "ref-display-inline-flex",
    "align-items": "ref-align-center",
    gap: "ref-spacing-xs",
    background: "sys-primary",
    "background-hover": "sys-primary-hover",
    "background-active": "sys-primary-active",
    "background-focus": "sys-primary",
    text: "sys-on-primary",
    "text-hover": "sys-on-primary",
    "text-active": "sys-on-primary",
    "text-focus": "sys-on-primary",
    "font-size": "ref-text-base",
    "font-weight": "ref-font-bold",
    "font-weight-hover": "ref-font-bold",
    "font-weight-active": "ref-font-bold",
    "font-weight-focus": "ref-font-bold",
    "white-space": "ref-whitespace-nowrap",
    "padding-left": "ref-spacing-sm",
    "padding-right": "ref-spacing-sm",
    "padding-top": "ref-spacing-xs",
    "padding-bottom": "ref-spacing-xs",
    "border-top-width": "ref-border-width-thin",
    "border-right-width": "ref-border-width-thin",
    "border-bottom-width": "ref-border-width-thin",
    "border-left-width": "ref-border-width-thin",
    "border-top-style": "ref-border-style-solid",
    "border-right-style": "ref-border-style-solid",
    "border-bottom-style": "ref-border-style-solid",
    "border-left-style": "ref-border-style-solid",
    "border-color": "sys-outline",
    cursor: "ref-cursor-pointer",
    "box-shadow-focus": "ref-shadow-focus-ring",
    "opacity-disabled": "ref-opacity-50",
    "cursor-disabled": "ref-cursor-default",
  }),
];
