import { fab } from "@foundation/blocks/elements";
import { createTokenDef } from "./helpers";

export default [
  createTokenDef(fab.key, {
    background: "ref-color-transparent",
    text: "sys-on-surface-variant",
    "text-hover": "sys-on-surface",
    "text-active": "sys-on-surface",
    "text-selected": "sys-primary",
    "text-selected-hover": "sys-primary",
    "text-selected-active": "sys-primary",
    "text-selected-focus": "sys-primary",
    "background-hover": "sys-hover",
    "background-active": "sys-active",
    "background-selected-hover": "sys-hover",
    "background-selected-active": "sys-active",
    "background-selected-focus": "ref-color-transparent",
    "box-shadow-selected-focus": "ref-shadow-focus-inset",
    cursor: "ref-cursor-pointer",
    "padding-left": "ref-spacing-lg",
    "padding-right": "ref-spacing-lg",
    "padding-top": "ref-spacing-md",
    "padding-bottom": "ref-spacing-md",
    "outline-color": "sys-focus",
    "outline-width": "ref-outline-width-medium",
    "font-weight": "ref-font-bold",
    "font-weight-hover": "ref-font-bold",
    "font-weight-active": "ref-font-bold",
    "font-weight-focus": "ref-font-bold",
    "background-focus": "ref-color-transparent",
    "box-shadow-focus": "ref-shadow-focus-inset",
    "opacity-disabled": "ref-opacity-50",
    "cursor-disabled": "ref-cursor-default",
  }),
];
