import { navigator } from "@foundation/blocks/elements";
import { createTokenDef } from "./helpers";

export default [
  createTokenDef(navigator.root, {
    display: "ref-display-flex",
    "align-items": "ref-align-center",
    position: "ref-position-relative",
  }),

  createTokenDef(navigator.list, {
    display: "ref-display-flex",
    "flex-direction": "ref-flex-row",
    "align-items": "ref-align-center",
    gap: "ref-spacing-none",
  }),

  createTokenDef(navigator.item, {
    display: "ref-display-flex",
  }),

  createTokenDef(navigator.trigger, {
    background: "ref-color-transparent",
    text: "sys-on-surface-variant",
    "text-hover": "sys-on-surface",
    "text-active": "sys-on-surface",
    "text-open": "sys-on-surface",
    "text-open-hover": "sys-on-surface",
    "text-open-active": "sys-on-surface",
    "text-selected": "sys-primary",
    "text-selected-hover": "sys-primary",
    "text-selected-active": "sys-primary",
    "background-open": "sys-surface-container-high",
    "background-hover": "sys-hover",
    "background-open-hover": "sys-hover",
    "background-selected": "ref-color-transparent",
    "background-selected-hover": "sys-hover",
    "box-shadow-selected": "ref-shadow-border-bottom",
    "box-shadow-selected-hover": "ref-shadow-border-bottom",
    "box-shadow-selected-active": "ref-shadow-border-bottom",
    cursor: "ref-cursor-pointer",
    "font-size": "ref-text-base",
    "font-weight": "ref-font-bold",
    "font-weight-hover": "ref-font-bold",
    "font-weight-active": "ref-font-bold",
    "font-weight-focus": "ref-font-bold",
    "font-weight-open": "ref-font-bold",
    "font-weight-open-hover": "ref-font-bold",
    "font-weight-open-active": "ref-font-bold",
    "font-weight-open-focus": "ref-font-bold",
    "font-weight-selected": "ref-font-bold",
    "font-weight-selected-hover": "ref-font-bold",
    "font-weight-selected-active": "ref-font-bold",
    "font-weight-selected-focus": "ref-font-bold",
    "padding-left": "ref-spacing-lg",
    "padding-right": "ref-spacing-lg",
    "padding-top": "ref-spacing-md",
    "padding-bottom": "ref-spacing-md",
    display: "ref-display-flex",
    "align-items": "ref-align-center",
    "justify-content": "ref-justify-center",
    gap: "ref-spacing-xs",
    "background-focus": "sys-hover",
    "box-shadow-focus": "ref-shadow-focus-inset",
    "background-open-focus": "sys-hover",
    "box-shadow-open-focus": "ref-shadow-focus-inset",
    "background-selected-focus": "sys-hover",
    "box-shadow-selected-focus": "ref-shadow-border-bottom-focus",
  }),

  createTokenDef(navigator.link, {
    background: "ref-color-transparent",
    text: "sys-on-surface-variant",
    "text-hover": "sys-on-surface",
    "text-active": "sys-on-surface",
    "text-focus": "sys-on-surface",
    "text-selected": "sys-primary",
    "text-selected-hover": "sys-primary",
    "text-selected-active": "sys-primary",
    "text-selected-focus": "sys-primary",
    "background-hover": "sys-hover",
    "background-selected": "ref-color-transparent",
    "background-selected-hover": "sys-hover",
    "box-shadow-selected": "ref-shadow-border-bottom",
    "box-shadow-selected-hover": "ref-shadow-border-bottom",
    "box-shadow-selected-active": "ref-shadow-border-bottom",
    cursor: "ref-cursor-pointer",
    "font-size": "ref-text-base",
    "font-weight": "ref-font-bold",
    "font-weight-hover": "ref-font-bold",
    "font-weight-active": "ref-font-bold",
    "font-weight-focus": "ref-font-bold",
    "font-weight-selected": "ref-font-bold",
    "font-weight-selected-hover": "ref-font-bold",
    "font-weight-selected-active": "ref-font-bold",
    "font-weight-selected-focus": "ref-font-bold",
    "padding-left": "ref-spacing-lg",
    "padding-right": "ref-spacing-lg",
    "padding-top": "ref-spacing-md",
    "padding-bottom": "ref-spacing-md",
    display: "ref-display-flex",
    "align-items": "ref-align-center",
    gap: "ref-spacing-xs",
    "text-decoration": "ref-decoration-none",
    "background-focus": "sys-hover",
    "box-shadow-focus": "ref-shadow-focus-inset",
    "background-selected-focus": "sys-hover",
    "box-shadow-selected-focus": "ref-shadow-border-bottom-focus",
  }),

  createTokenDef(navigator.content, {
    background: "sys-surface-container",
    text: "sys-on-surface",
    "padding-top": "ref-spacing-sm",
    "padding-right": "ref-spacing-sm",
    "padding-bottom": "ref-spacing-sm",
    "padding-left": "ref-spacing-sm",
    "border-top-width": "ref-border-width-thin",
    "border-right-width": "ref-border-width-thin",
    "border-bottom-width": "ref-border-width-thin",
    "border-left-width": "ref-border-width-thin",
    "border-top-style": "ref-border-style-solid",
    "border-right-style": "ref-border-style-solid",
    "border-bottom-style": "ref-border-style-solid",
    "border-left-style": "ref-border-style-solid",
    "border-color": "sys-outline",
    display: "ref-display-flex",
    "flex-direction": "ref-flex-col",
    gap: "ref-spacing-none",
    width: "ref-max",
  }),

  createTokenDef(navigator.viewport, {
    position: "ref-position-absolute",
    top: "ref-position-zero",
    "overflow-x": "ref-overflow-hidden",
    "overflow-y": "ref-overflow-hidden",
  }),

  createTokenDef(navigator.viewportWrapper, {
    position: "ref-position-absolute",
    top: "ref-position-full-gap-sm",
    left: "ref-position-zero",
    "z-index": "ref-z-dropdown",
    display: "ref-display-flex",
    "justify-content": "ref-justify-start",
    width: "ref-full",
  }),

  createTokenDef(navigator.indicator, {
    background: "sys-primary",
    height: "ref-hairline",
    position: "ref-position-absolute",
    bottom: "ref-position-zero",
    "z-index": "ref-z-base",
  }),

  createTokenDef(navigator.grid, {
    display: "ref-display-grid",
    "grid-template-columns": "ref-layout-sidebar-left",
    "grid-template-rows": "ref-layout-split",
    gap: "ref-spacing-sm",
  }),

  createTokenDef(navigator.card, {
    background: "sys-surface-container",
    text: "sys-on-surface-variant",
    "text-hover": "sys-on-surface",
    "text-active": "sys-on-surface",
    "text-focus": "sys-on-surface",
    "background-hover": "sys-surface-container-high",
    cursor: "ref-cursor-pointer",
    "font-size": "ref-text-base",
    "font-weight": "ref-font-bold",
    "font-weight-hover": "ref-font-bold",
    "font-weight-active": "ref-font-bold",
    "font-weight-focus": "ref-font-bold",
    "padding-left": "ref-spacing-md",
    "padding-right": "ref-spacing-md",
    "padding-top": "ref-spacing-md",
    "padding-bottom": "ref-spacing-md",
    display: "ref-display-flex",
    "flex-direction": "ref-flex-col",
    "align-items": "ref-align-start",
    "justify-content": "ref-justify-start",
    gap: "ref-spacing-xs",
    "text-decoration": "ref-decoration-none",
    "border-top-width": "ref-border-width-thin",
    "border-right-width": "ref-border-width-thin",
    "border-bottom-width": "ref-border-width-thin",
    "border-left-width": "ref-border-width-thin",
    "border-top-style": "ref-border-style-solid",
    "border-right-style": "ref-border-style-solid",
    "border-bottom-style": "ref-border-style-solid",
    "border-left-style": "ref-border-style-solid",
    "border-color": "sys-outline",
    "background-focus": "sys-surface-container-high",
    "box-shadow-focus": "ref-shadow-focus-inset",
    "transition-duration": "ref-duration-fast",
    "transition-easing": "ref-ease-out",
  }),

  createTokenDef(navigator.featured, {
    background: "sys-surface-container-high",
    text: "sys-on-surface-variant",
    "text-hover": "sys-on-surface",
    "text-active": "sys-on-surface",
    "text-focus": "sys-on-surface",
    "background-hover": "sys-surface-container-highest",
    cursor: "ref-cursor-pointer",
    "font-size": "ref-text-lg",
    "font-weight": "ref-font-bold",
    "font-weight-hover": "ref-font-bold",
    "font-weight-active": "ref-font-bold",
    "font-weight-focus": "ref-font-bold",
    "padding-left": "ref-spacing-lg",
    "padding-right": "ref-spacing-lg",
    "padding-top": "ref-spacing-lg",
    "padding-bottom": "ref-spacing-lg",
    display: "ref-display-flex",
    "flex-direction": "ref-flex-col",
    "align-items": "ref-align-start",
    "justify-content": "ref-justify-start",
    gap: "ref-spacing-sm",
    "text-decoration": "ref-decoration-none",
    "border-top-width": "ref-border-width-thin",
    "border-right-width": "ref-border-width-thin",
    "border-bottom-width": "ref-border-width-thin",
    "border-left-width": "ref-border-width-thin",
    "border-top-style": "ref-border-style-solid",
    "border-right-style": "ref-border-style-solid",
    "border-bottom-style": "ref-border-style-solid",
    "border-left-style": "ref-border-style-solid",
    "border-color": "sys-outline",
    "grid-row": "ref-grid-row-span-all",
    "background-focus": "sys-surface-container-highest",
    "box-shadow-focus": "ref-shadow-focus-inset",
    "transition-duration": "ref-duration-fast",
    "transition-easing": "ref-ease-out",
  }),

  createTokenDef(navigator.cardDescription, {
    "font-size": "ref-text-xs",
    "font-weight": "ref-font-normal",
  }),

  createTokenDef(navigator.featuredDescription, {
    "font-size": "ref-text-sm",
    "font-weight": "ref-font-normal",
  }),
];
