import { select } from "@foundation/blocks/elements";
import { createTokenDef } from "./helpers";

export default [
  createTokenDef(select.root, {
    background: "ref-color-transparent",
  }),

  createTokenDef(select.trigger, {
    display: "ref-display-flex",
    "align-items": "ref-align-center",
    "justify-content": "ref-justify-between",
    gap: "ref-spacing-xs",
    background: "sys-surface",
    text: "sys-on-surface",
    "font-size": "ref-text-base",
    "font-weight": "ref-font-normal",
    "padding-top": "ref-spacing-sm",
    "padding-right": "ref-spacing-md",
    "padding-bottom": "ref-spacing-sm",
    "padding-left": "ref-spacing-md",
    "border-top-width": "ref-border-width-thin",
    "border-right-width": "ref-border-width-thin",
    "border-bottom-width": "ref-border-width-thin",
    "border-left-width": "ref-border-width-thin",
    "border-top-style": "ref-border-style-solid",
    "border-right-style": "ref-border-style-solid",
    "border-bottom-style": "ref-border-style-solid",
    "border-left-style": "ref-border-style-solid",
    "border-color": "sys-outline",
    "border-color-hover": "sys-outline",
    "border-color-focus": "sys-primary",
    "background-hover": "sys-hover",
    "background-focus": "sys-surface",
    "box-shadow-focus": "ref-shadow-focus-ring",
    cursor: "ref-cursor-pointer",
    width: "ref-full",
    "transition-duration": "ref-duration-fast",
    "transition-easing": "ref-ease-out",
  }),

  createTokenDef(select.content, {
    background: "sys-surface-container",
    text: "sys-on-surface",
    "padding-top": "ref-spacing-xs",
    "padding-right": "ref-spacing-xs",
    "padding-bottom": "ref-spacing-xs",
    "padding-left": "ref-spacing-xs",
    "border-top-width": "ref-border-width-thin",
    "border-right-width": "ref-border-width-thin",
    "border-bottom-width": "ref-border-width-thin",
    "border-left-width": "ref-border-width-thin",
    "border-top-style": "ref-border-style-solid",
    "border-right-style": "ref-border-style-solid",
    "border-bottom-style": "ref-border-style-solid",
    "border-left-style": "ref-border-style-solid",
    "border-color": "sys-outline",
    "z-index": "ref-z-dropdown",
    "max-height": "ref-width-md",
    "overflow-y": "ref-overflow-auto",
  }),

  createTokenDef(select.item, {
    background: "ref-color-transparent",
    text: "sys-on-surface",
    "text-hover": "sys-on-surface",
    "text-selected": "sys-primary",
    "text-selected-hover": "sys-primary",
    "background-hover": "sys-hover",
    "background-selected": "sys-surface-container-high",
    "background-selected-hover": "sys-hover",
    "padding-top": "ref-spacing-xs",
    "padding-right": "ref-spacing-md",
    "padding-bottom": "ref-spacing-xs",
    "padding-left": "ref-spacing-md",
    cursor: "ref-cursor-pointer",
    "font-size": "ref-text-base",
    "background-focus": "sys-hover",
    "box-shadow-focus": "ref-shadow-focus-inset",
    "background-selected-focus": "sys-hover",
    "transition-duration": "ref-duration-fast",
    "transition-easing": "ref-ease-out",
  }),
];
