import { surround } from "@foundation/prose/elements";
import { createTokenDef } from "./helpers";

export default [
  createTokenDef(surround.root, {
    display: "ref-display-flex",
    "flex-direction": "ref-flex-row",
    width: "ref-full",
    gap: "ref-spacing-md",
  }),

  createTokenDef(surround.prev, {
    display: "ref-display-flex",
    "flex-direction": "ref-flex-col",
    "align-items": "ref-align-start",
    "justify-content": "ref-justify-center",
    "flex-grow": "ref-flex-grow",
    "flex-basis": "ref-flex-basis-half",
    gap: "ref-spacing-xs",
    "padding-top": "ref-spacing-md",
    "padding-right": "ref-spacing-lg",
    "padding-bottom": "ref-spacing-md",
    "padding-left": "ref-spacing-lg",
    "text-decoration": "ref-decoration-none",
    "border-top-width": "ref-border-width-thin",
    "border-right-width": "ref-border-width-thin",
    "border-bottom-width": "ref-border-width-thin",
    "border-left-width": "ref-border-width-thin",
    "border-top-style": "ref-border-style-solid",
    "border-right-style": "ref-border-style-solid",
    "border-bottom-style": "ref-border-style-solid",
    "border-left-style": "ref-border-style-solid",
    "border-color": "sys-outline",
    "border-color-hover": "sys-outline",
    "border-color-active": "sys-outline",
    "border-color-focus": "sys-outline",
    "background-hover": "sys-hover",
    "background-focus": "ref-color-transparent",
    "box-shadow-focus": "ref-shadow-focus-inset",
    cursor: "ref-cursor-pointer",
    "transition-duration": "ref-duration-fast",
    "transition-easing": "ref-ease-out",
  }),

  createTokenDef(surround.next, {
    display: "ref-display-flex",
    "flex-direction": "ref-flex-col",
    "align-items": "ref-align-end",
    "justify-content": "ref-justify-center",
    "flex-grow": "ref-flex-grow",
    "flex-basis": "ref-flex-basis-half",
    gap: "ref-spacing-xs",
    "padding-top": "ref-spacing-md",
    "padding-right": "ref-spacing-lg",
    "padding-bottom": "ref-spacing-md",
    "padding-left": "ref-spacing-lg",
    "text-decoration": "ref-decoration-none",
    "border-top-width": "ref-border-width-thin",
    "border-right-width": "ref-border-width-thin",
    "border-bottom-width": "ref-border-width-thin",
    "border-left-width": "ref-border-width-thin",
    "border-top-style": "ref-border-style-solid",
    "border-right-style": "ref-border-style-solid",
    "border-bottom-style": "ref-border-style-solid",
    "border-left-style": "ref-border-style-solid",
    "border-color": "sys-outline",
    "border-color-hover": "sys-outline",
    "border-color-active": "sys-outline",
    "border-color-focus": "sys-outline",
    "background-hover": "sys-hover",
    "background-focus": "ref-color-transparent",
    "box-shadow-focus": "ref-shadow-focus-inset",
    cursor: "ref-cursor-pointer",
    "transition-duration": "ref-duration-fast",
    "transition-easing": "ref-ease-out",
  }),

  createTokenDef(surround.label, {
    display: "ref-display-inline-flex",
    "align-items": "ref-align-center",
    gap: "ref-spacing-2xs",
    text: "sys-on-surface-variant",
    "font-size": "ref-text-sm",
    "font-weight": "ref-font-medium",
  }),

  createTokenDef(surround.title, {
    text: "sys-on-surface",
    "font-size": "ref-text-base",
    "font-weight": "ref-font-bold",
  }),

  createTokenDef(surround.prevDescription, {
    text: "sys-on-surface-variant",
    "font-size": "ref-text-sm",
    "font-weight": "ref-font-normal",
  }),

  createTokenDef(surround.nextDescription, {
    text: "sys-on-surface-variant",
    "font-size": "ref-text-sm",
    "font-weight": "ref-font-normal",
    "text-align": "ref-text-align-end",
  }),
];
