import { tree } from "@foundation/blocks/elements";
import { createTokenDef } from "./helpers";

export default [
  createTokenDef(tree.root, {
    display: "ref-display-flex",
    "flex-direction": "ref-flex-col",
  }),

  createTokenDef(tree.branch, {
    display: "ref-display-flex",
    "flex-direction": "ref-flex-col",
    background: "ref-color-transparent",
    text: "sys-on-surface-variant",
    "text-hover": "sys-on-surface",
    "text-open": "sys-on-surface",
    "text-open-hover": "sys-on-surface",
    "background-hover": "sys-hover",
    cursor: "ref-cursor-pointer",
    "font-size": "ref-text-base",
    "font-weight": "ref-font-normal",
    "font-weight-hover": "ref-font-normal",
    "font-weight-active": "ref-font-normal",
    "font-weight-focus": "ref-font-normal",
    "font-weight-open": "ref-font-normal",
    "font-weight-open-hover": "ref-font-normal",
    "font-weight-open-active": "ref-font-normal",
    "font-weight-open-focus": "ref-font-normal",
    "background-focus": "sys-hover",
    "box-shadow-focus": "ref-shadow-focus-inset",
    "background-open-focus": "sys-hover",
    "box-shadow-open-focus": "ref-shadow-focus-inset",
  }),

  createTokenDef(tree.branchContent, {
    display: "ref-display-flex",
    "flex-direction": "ref-flex-row",
    "align-items": "ref-align-center",
    "justify-content": "ref-justify-between",
    gap: "ref-spacing-xs",
    "padding-left": "ref-spacing-md",
    "padding-right": "ref-spacing-md",
    "padding-top": "ref-spacing-xs",
    "padding-bottom": "ref-spacing-xs",
  }),

  createTokenDef(tree.leaf, {
    background: "ref-color-transparent",
    text: "sys-on-surface-variant",
    "text-hover": "sys-on-surface",
    "text-active": "sys-primary",
    "text-selected": "sys-primary",
    "text-selected-hover": "sys-primary",
    "background-hover": "sys-hover",
    "background-selected": "sys-surface-container-high",
    "background-selected-hover": "sys-hover",
    "box-shadow-selected": "ref-shadow-border-left",
    "box-shadow-selected-hover": "ref-shadow-border-left",
    "box-shadow-selected-active": "ref-shadow-border-left",
    "border-color": "ref-color-transparent",
    cursor: "ref-cursor-pointer",
    "font-size": "ref-text-base",
    "text-selected-active": "sys-primary",
    "text-selected-focus": "sys-primary",
    display: "ref-display-flex",
    "flex-direction": "ref-flex-col",
    "background-focus": "sys-hover",
    "box-shadow-focus": "ref-shadow-focus-inset",
    "background-selected-focus": "sys-hover",
    "box-shadow-selected-focus": "ref-shadow-border-left-focus",
  }),

  createTokenDef(tree.leafContent, {
    display: "ref-display-flex",
    "flex-direction": "ref-flex-row",
    "align-items": "ref-align-center",
    gap: "ref-spacing-xs",
    "padding-left": "ref-spacing-md",
    "padding-right": "ref-spacing-md",
    "padding-top": "ref-spacing-xs",
    "padding-bottom": "ref-spacing-xs",
    text: "ref-inherit",
    "text-decoration": "ref-decoration-none",
    "font-weight": "ref-font-normal",
  }),
];
