import {
  p,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  code,
  kbd,
  pre,
  strong,
  em,
  del,
  blockquote,
  hr,
  ul,
  ol,
  li,
} from "@foundation/blocks/elements";
import { createTokenDef } from "./helpers";

export default [
  createTokenDef(p.key, {
    text: "sys-on-surface",
    "font-size": "ref-text-base",
    "font-weight": "ref-font-normal",
    "line-height": "ref-leading-normal",
    display: "ref-display-block",
    "margin-top": "ref-spacing-base",
    "margin-bottom": "ref-spacing-base",
  }),

  createTokenDef(h1.key, {
    text: "sys-on-surface",
    "font-size": "ref-text-4xl",
    "font-weight": "ref-font-bold",
    "line-height": "ref-leading-tighter",
    display: "ref-display-block",
    "margin-top": "ref-spacing-none",
    "margin-bottom": "ref-spacing-xl",
  }),

  createTokenDef(h2.key, {
    text: "sys-on-surface",
    "font-size": "ref-text-2xl",
    "font-weight": "ref-font-bold",
    "line-height": "ref-leading-snug",
    display: "ref-display-block",
    "margin-top": "ref-spacing-2xl",
    "margin-bottom": "ref-spacing-lg",
    "scroll-margin-top": "ref-scroll-lg",
  }),

  createTokenDef(h3.key, {
    text: "sys-on-surface",
    "font-size": "ref-text-2xl",
    "font-weight": "ref-font-semibold",
    "line-height": "ref-leading-cozy",
    display: "ref-display-block",
    "margin-top": "ref-spacing-xl",
    "margin-bottom": "ref-spacing-sm",
    "scroll-margin-top": "ref-scroll-lg",
  }),

  createTokenDef(h4.key, {
    text: "sys-on-surface",
    "font-size": "ref-text-base",
    "font-weight": "ref-font-semibold",
    "line-height": "ref-leading-normal",
    display: "ref-display-block",
    "margin-top": "ref-spacing-lg",
    "margin-bottom": "ref-spacing-xs",
    "scroll-margin-top": "ref-scroll-lg",
  }),

  createTokenDef(h5.key, {
    text: "sys-on-surface-variant",
    "font-size": "ref-text-base",
    "font-weight": "ref-font-semibold",
    "line-height": "ref-leading-normal",
    display: "ref-display-block",
    "margin-top": "ref-spacing-lg",
    "margin-bottom": "ref-spacing-xs",
    "scroll-margin-top": "ref-scroll-lg",
  }),

  createTokenDef(h6.key, {
    text: "sys-on-surface-variant",
    "font-size": "ref-text-base",
    "font-weight": "ref-font-medium",
    "line-height": "ref-leading-normal",
    display: "ref-display-block",
    "margin-top": "ref-spacing-lg",
    "margin-bottom": "ref-spacing-xs",
    "scroll-margin-top": "ref-scroll-lg",
  }),

  createTokenDef(code.key, {
    text: "sys-on-surface",
    background: "sys-surface-container",
    "font-family": "ref-font-mono",
    "font-size": "ref-text-sm",
    "padding-top": "ref-spacing-none",
    "padding-right": "ref-spacing-2xs",
    "padding-bottom": "ref-spacing-none",
    "padding-left": "ref-spacing-2xs",
    "border-top-width": "ref-border-width-thin",
    "border-right-width": "ref-border-width-thin",
    "border-bottom-width": "ref-border-width-thin",
    "border-left-width": "ref-border-width-thin",
    "border-top-style": "ref-border-style-solid",
    "border-right-style": "ref-border-style-solid",
    "border-bottom-style": "ref-border-style-solid",
    "border-left-style": "ref-border-style-solid",
    "border-color": "sys-outline",
    display: "ref-display-inline-block",
  }),

  createTokenDef(kbd.key, {
    text: "sys-on-surface",
    background: "sys-surface-container-high",
    "font-family": "ref-font-mono",
    "font-size": "ref-text-xs",
    "font-weight": "ref-font-semibold",
    "padding-top": "ref-spacing-2xs",
    "padding-right": "ref-spacing-2xs",
    "padding-bottom": "ref-spacing-2xs",
    "padding-left": "ref-spacing-2xs",
    "border-top-width": "ref-border-width-thin",
    "border-right-width": "ref-border-width-thin",
    "border-bottom-width": "ref-border-width-thin",
    "border-left-width": "ref-border-width-thin",
    "border-top-style": "ref-border-style-solid",
    "border-right-style": "ref-border-style-solid",
    "border-bottom-style": "ref-border-style-solid",
    "border-left-style": "ref-border-style-solid",
    "border-color": "sys-outline",
    display: "ref-display-inline-flex",
    "align-items": "ref-align-center",
    gap: "ref-spacing-2xs",
    "white-space": "ref-whitespace-nowrap",
  }),

  createTokenDef(pre.key, {
    text: "sys-on-surface",
    background: "sys-surface-container",
    "font-family": "ref-font-mono",
    "font-size": "ref-text-sm",
    "padding-top": "ref-spacing-md",
    "padding-right": "ref-spacing-md",
    "padding-bottom": "ref-spacing-md",
    "padding-left": "ref-spacing-md",
    "border-top-width": "ref-border-width-thin",
    "border-right-width": "ref-border-width-thin",
    "border-bottom-width": "ref-border-width-thin",
    "border-left-width": "ref-border-width-thin",
    "border-top-style": "ref-border-style-solid",
    "border-right-style": "ref-border-style-solid",
    "border-bottom-style": "ref-border-style-solid",
    "border-left-style": "ref-border-style-solid",
    "border-color": "sys-outline",
    display: "ref-display-block",
    "overflow-x": "ref-overflow-auto",
    "margin-top": "ref-spacing-base",
    "margin-bottom": "ref-spacing-base",
  }),

  createTokenDef(strong.key, {
    "font-weight": "ref-font-bold",
    display: "ref-display-inline",
  }),

  createTokenDef(em.key, {
    "font-style": "ref-font-italic",
    display: "ref-display-inline",
  }),

  createTokenDef(del.key, {
    "text-decoration": "ref-decoration-line-through",
    display: "ref-display-inline",
  }),

  createTokenDef(blockquote.key, {
    text: "sys-on-surface-variant",
    "font-style": "ref-font-italic",
    "border-left-width": "ref-border-width-heavy",
    "border-left-style": "ref-border-style-solid",
    "border-color": "sys-outline",
    "padding-left": "ref-spacing-lg",
    "margin-top": "ref-spacing-xl",
    "margin-bottom": "ref-spacing-xl",
    display: "ref-display-block",
  }),

  createTokenDef(hr.key, {
    "border-top-width": "ref-border-width-thin",
    "border-top-style": "ref-border-style-solid",
    "border-color": "sys-outline",
    display: "ref-display-block",
  }),

  createTokenDef(ul.key, {
    "list-style-type": "ref-list-disc",
    "padding-left": "ref-spacing-xl",
    "margin-top": "ref-spacing-base",
    "margin-bottom": "ref-spacing-base",
    display: "ref-display-block",
  }),

  createTokenDef(ol.key, {
    "list-style-type": "ref-list-decimal",
    "padding-left": "ref-spacing-xl",
    "margin-top": "ref-spacing-base",
    "margin-bottom": "ref-spacing-base",
    display: "ref-display-block",
  }),

  createTokenDef(li.key, {
    display: "ref-display-list-item",
    "margin-top": "ref-spacing-xs",
    "margin-bottom": "ref-spacing-xs",
  }),
];
