import { versionSelect } from "../../elements.config";
import { createTokenDef } from "./helpers";

export default [
  createTokenDef(versionSelect.root, {
    background: "ref-color-transparent",
  }),

  createTokenDef(versionSelect.trigger, {
    display: "ref-display-inline-flex",
    "align-items": "ref-align-center",
    gap: "ref-spacing-2xs",
    background: "sys-primary",
    "background-hover": "sys-primary-hover",
    "background-active": "sys-primary-active",
    text: "sys-on-primary",
    "text-hover": "sys-on-primary",
    "text-active": "sys-on-primary",
    "font-size": "ref-text-sm",
    "font-weight": "ref-font-normal",
    "font-weight-hover": "ref-font-normal",
    "font-weight-active": "ref-font-normal",
    "white-space": "ref-whitespace-nowrap",
    "padding-left": "ref-spacing-xs",
    "padding-right": "ref-spacing-xs",
    "padding-top": "ref-spacing-2xs",
    "padding-bottom": "ref-spacing-2xs",
    "border-top-width": "ref-border-width-thin",
    "border-right-width": "ref-border-width-thin",
    "border-bottom-width": "ref-border-width-thin",
    "border-left-width": "ref-border-width-thin",
    "border-top-style": "ref-border-style-solid",
    "border-right-style": "ref-border-style-solid",
    "border-bottom-style": "ref-border-style-solid",
    "border-left-style": "ref-border-style-solid",
    "border-color": "sys-outline",
    cursor: "ref-cursor-pointer",
    "transition-duration": "ref-duration-fast",
    "transition-easing": "ref-ease-out",
  }),

  createTokenDef(versionSelect.content, {
    background: "sys-surface-container",
    text: "sys-on-surface",
    "padding-top": "ref-spacing-xs",
    "padding-right": "ref-spacing-xs",
    "padding-bottom": "ref-spacing-xs",
    "padding-left": "ref-spacing-xs",
    "border-top-width": "ref-border-width-thin",
    "border-right-width": "ref-border-width-thin",
    "border-bottom-width": "ref-border-width-thin",
    "border-left-width": "ref-border-width-thin",
    "border-top-style": "ref-border-style-solid",
    "border-right-style": "ref-border-style-solid",
    "border-bottom-style": "ref-border-style-solid",
    "border-left-style": "ref-border-style-solid",
    "border-color": "sys-outline",
    "z-index": "ref-z-dropdown",
    "max-height": "ref-width-md",
    "overflow-y": "ref-overflow-auto",
  }),

  createTokenDef(versionSelect.item, {
    background: "ref-color-transparent",
    text: "sys-on-surface",
    "text-hover": "sys-on-surface",
    "text-selected": "sys-primary",
    "text-selected-hover": "sys-primary",
    "background-hover": "sys-hover",
    "background-selected": "sys-surface-container-high",
    "background-selected-hover": "sys-hover",
    "padding-top": "ref-spacing-xs",
    "padding-right": "ref-spacing-md",
    "padding-bottom": "ref-spacing-xs",
    "padding-left": "ref-spacing-md",
    cursor: "ref-cursor-pointer",
    "font-size": "ref-text-sm",
    "background-focus": "sys-hover",
    "box-shadow-focus": "ref-shadow-focus-inset",
    "background-selected-focus": "sys-hover",
    "transition-duration": "ref-duration-fast",
    "transition-easing": "ref-ease-out",
  }),
];
