import { describe, it, expect } from "vitest";
import { generateModifierTypes } from "#modules/modifiers/template";
import components from "#config/components";

describe("generateModifierTypes", () => {
  it("emits the generated-file header and interface declaration", () => {
    const out = generateModifierTypes({});
    expect(out).toContain("// Generated by the `modifiers` module — do not edit.");
    expect(out).toContain("export interface ComponentModifiers {");
  });

  it("emits every supported component as a key", () => {
    const out = generateModifierTypes({});
    for (const component of components.elements) {
      expect(out).toContain(`  ${component}:`);
    }
  });

  it("maps unsupplied components to never", () => {
    const out = generateModifierTypes({ button: { variant: ["solid"] } });
    expect(out).toContain("  alert: never;");
    expect(out).toContain("  tr: never;");
    expect(out).not.toContain("  button: never;");
  });

  it("maps every component to never when the schema is empty", () => {
    const out = generateModifierTypes({});
    for (const component of components.elements) {
      expect(out).toContain(`  ${component}: never;`);
    }
  });

  it("renders a supplied component's axes as readonly tuples", () => {
    const out = generateModifierTypes({
      button: {
        variant: ["solid", "outline", "ghost"],
        tone: ["primary", "danger"],
      },
    });
    expect(out).toContain('    variant: readonly ["solid", "outline", "ghost"];');
    expect(out).toContain('    tone: readonly ["primary", "danger"];');
    expect(out).toMatch(
      / {2}button: \{\n {4}variant: .+\n {4}tone: .+\n {2}\};/,
    );
  });

  it("renders a single-value axis as a one-member tuple", () => {
    const out = generateModifierTypes({ h1: { level: ["display"] } });
    expect(out).toContain('    level: readonly ["display"];');
  });

  it("treats a component with no axes as never", () => {
    const out = generateModifierTypes({ button: {} });
    expect(out).toContain("  button: never;");
  });

  it("produces balanced braces", () => {
    const out = generateModifierTypes({
      button: { variant: ["a", "b"] },
      h1: { level: ["x"] },
    });
    const open = (out.match(/\{/g) ?? []).length;
    const close = (out.match(/\}/g) ?? []).length;
    expect(open).toBe(close);
  });
});
