import { computed } from "vue";
import { useState, useNuxtApp } from "#app";
import { useRoute } from "#imports";
import "../src/hooks";

// @ts-ignore — virtual module generated by the rosetta Nuxt module
import { defaultLocale, locales } from "#build/rosetta.config.mjs";

/** Reactive locale state. */
export const useI18n = () => {
  const locale = useState<string>("rosetta:locale", () => defaultLocale);
  const messages = useState<Record<string, string>>("rosetta:messages", () => ({}));
  const nuxtApp = useNuxtApp();

  const setLocale = async (code: string) => {
    const prev = locale.value;
    locale.value = code;
    const route = useRoute().path;
    await loadChunk(locale.value, route, messages);
    nuxtApp.callHook("rosetta:locale", { from: prev, to: code });
  };

  return {
    locale,
    locales: computed<string[]>(() => locales),
    messages,
    setLocale,
  };
};

/**
 * Translation function — auto-imported for use in templates.
 * Reads from the reactive messages store; Vue tracks the dependency
 * when called during render, ensuring re-render on locale change.
 */
export const $t = (text: string, params?: Record<string, unknown>): string => {
  const messages = useState<Record<string, string>>("rosetta:messages");
  const resolved = messages.value[text] ?? text;

  if (!params) return resolved;

  return resolved.replace(/\{(\w+)\}/g, (_, key: string) =>
    key in params ? String(params[key]) : `{${key}}`,
  );
};

const encodeRoute = (route: string): string =>
  encodeURIComponent(route === "/" ? "index" : route.slice(1));

/** Fetches a route chunk and merges into the messages store. */
export const loadChunk = async (
  locale: string,
  route: string,
  messages: { value: Record<string, string> },
): Promise<void> => {
  const encoded = encodeRoute(route);

  if (import.meta.server) {
    const { readChunk } = await import("./chunk");
    const routeChunk = readChunk(locale, encoded);
    const commonChunk = readChunk(locale, "__common");
    messages.value = { ...messages.value, ...commonChunk, ...routeChunk };
  } else {
    const [routeChunk, commonChunk] = await Promise.all([
      $fetch<Record<string, string>>(`/api/lang/${locale}/${encoded}`),
      $fetch<Record<string, string>>(`/api/lang/${locale}/__common`),
    ]);
    messages.value = { ...messages.value, ...commonChunk, ...routeChunk };
  }

};
