/**
 * Selected state tokens (for list items, tabs, etc)
 */
export default {
  "background-selected": null,
  "text-selected": "sys-on-surface",
  "border-color-selected": null,
  "border-top-width-selected": null,
  "border-right-width-selected": null,
  "border-bottom-width-selected": null,
  "border-left-width-selected": null,
  "font-weight-selected": null,
  "box-shadow-selected": null,
  "background-selected-hover": "sys-hover",
  "text-selected-hover": "sys-on-surface",
  "border-color-selected-hover": null,
  "border-top-width-selected-hover": null,
  "border-right-width-selected-hover": null,
  "border-bottom-width-selected-hover": null,
  "border-left-width-selected-hover": null,
  "font-weight-selected-hover": null,
  "opacity-selected-hover": null,
  "box-shadow-selected-hover": null,
  "background-selected-active": "sys-active",
  "text-selected-active": "sys-on-surface",
  "border-color-selected-active": null,
  "border-top-width-selected-active": null,
  "border-right-width-selected-active": null,
  "border-bottom-width-selected-active": null,
  "border-left-width-selected-active": null,
  "font-weight-selected-active": null,
  "opacity-selected-active": null,
  "box-shadow-selected-active": null,
  "background-selected-focus": null,
  "text-selected-focus": null,
  "border-color-selected-focus": null,
  "border-top-width-selected-focus": null,
  "border-right-width-selected-focus": null,
  "border-bottom-width-selected-focus": null,
  "border-left-width-selected-focus": null,
  "font-weight-selected-focus": null,
  "box-shadow-selected-focus": null,
};
