import { useCookie, computed } from "#imports";
import { generateThemeCSS } from "../src/css";
import type { Theme } from "../src/config";

// @ts-expect-error virtual module generated by untheme Nuxt module
import { defaultTheme as buildDefault, themeNames, themes } from "#build/untheme.themes.mjs";

const names: string[] = themeNames ?? [];
const buildTheme: string = buildDefault ?? "";
const registry: Record<string, Theme> = themes ?? {};

export const useUntheme = () => {
  const mode = useCookie<"light" | "dark">("untheme-mode", { default: () => "dark" });
  const theme = useCookie<string>("untheme-theme", {
    default: () => {
      return buildTheme;
    },
  });

  // Validate stored theme against available themes
  if (theme.value && !names.includes(theme.value)) {
    theme.value = buildTheme;
  }

  const availableThemes = computed(() => names);

  const setTheme = (name: string) => {
    theme.value = name;
  };

  // Generate CSS for the active theme
  const themeCSS = computed(() => {
    const data = registry[theme.value];
    if (!data) return "";
    return generateThemeCSS(data);
  });

  return {
    mode,
    theme,
    setTheme,
    themes: availableThemes,
    themeCSS,
  };
};
