import { computed } from "vue";
import { useState, useNuxtApp } from "#app";
import "../src/hooks";
import { useCookie, useRequestFetch } from "#imports";
import { generateThemeCSS } from "../src/css";
import type { Theme, ThemeManifestEntry, CustomColor } from "../src/types";
import { isTheme, isCustomColor } from "../src/config";

// @ts-ignore — virtual module generated by the untheme Nuxt module
import {
  defaultTheme as buildDefault,
  manifest,
  defaultThemeData,
  colors as buildColors,
  roles as buildRoles,
} from "#build/untheme.config.mjs";

const buildTheme: string = buildDefault ?? "";
const buildManifest: ThemeManifestEntry[] = manifest ?? [];
const buildDefaultData: Theme | null = isTheme(defaultThemeData)
  ? defaultThemeData
  : null;
const buildColorMap: Record<string, CustomColor> = Object.fromEntries(
  Object.entries(buildColors ?? {}).filter(
    (entry): entry is [string, CustomColor] => isCustomColor(entry[1]),
  ),
);
const buildRoleMap: Record<string, string> = buildRoles ?? {};


export const useUntheme = () => {
  // App state — source of truth
  const theme = useState<string>("untheme:theme", () => buildTheme);
  const themeData = useState<Theme | null>(
    "untheme:data",
    () => buildDefaultData,
  );
  const mode = useState<"light" | "dark">("untheme:mode", () => "dark");

  // Cookie — persistence only, written as side effect
  const themeCookie = useCookie<string>("untheme-theme", {
    default: () => buildTheme,
  });
  const modeCookie = useCookie<"light" | "dark">("untheme-mode", {
    default: () => "dark",
  });

  const nuxtApp = useNuxtApp();
  const fetchWithCookies = useRequestFetch();

  // Fetch theme data and populate the store
  const load = async (): Promise<Theme | null> => {
    const key = theme.value;

    if (key === buildTheme && buildDefaultData) {
      themeData.value = buildDefaultData;
      return buildDefaultData;
    }

    const data = await fetchWithCookies<Theme>(`/api/untheme/${key}`);
    if (!isTheme(data)) {
      throw new Error(`[untheme] invalid theme data for "${key}"`);
    }
    themeData.value = data;
    return data;
  };

  // Seed app state from cookies — call once at app startup
  const init = async (): Promise<Theme | null> => {
    const keys = buildManifest.map((e) => e.key);

    // Seed mode from cookie
    if (modeCookie.value === "light" || modeCookie.value === "dark") {
      mode.value = modeCookie.value;
    }

    // Seed theme from cookie, validate against manifest
    if (themeCookie.value && keys.includes(themeCookie.value)) {
      theme.value = themeCookie.value;
    } else {
      theme.value = buildTheme;
    }

    return load();
  };

  const setTheme = async (name: string) => {
    const prev = theme.value;
    theme.value = name;
    themeCookie.value = name;
    await load();
    nuxtApp.callHook("untheme:theme", { from: prev, to: name });
  };

  const setMode = (value: "light" | "dark") => {
    const prev = mode.value;
    mode.value = value;
    modeCookie.value = value;
    nuxtApp.callHook("untheme:mode", { from: prev, to: value });
  };

  const toggleMode = () => {
    setMode(mode.value === "dark" ? "light" : "dark");
  };

  // Generate CSS from the active theme data
  const themeCSS = computed(() => {
    if (!themeData.value) return "";
    return generateThemeCSS(themeData.value, buildColorMap, buildRoleMap);
  });

  // Expose manifest entries (key + label) for UI components
  const themes = computed(() => buildManifest);

  return {
    mode,
    theme,
    cookies: {
      mode: modeCookie,
      theme: themeCookie,
    },
    init,
    load,
    setTheme,
    setMode,
    toggleMode,
    themes,
    themeCSS,
  };
};
