import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { defineNuxtModule, useNuxt } from "@nuxt/kit";
import type { VersionManifest } from "@foundation/github/sources/github-tags";

export interface VersionConfigOptions {
  /** Path to cache directory containing version-manifest.json (default: ".content-cache") */
  cacheDir?: string;
}

/**
 * Nuxt module that reads the version manifest generated by the GitHub tags source
 * and populates appConfig.version for runtime access.
 */
export default defineNuxtModule<VersionConfigOptions>({
  meta: {
    name: "version-config",
    configKey: "versionConfig",
  },
  defaults: {
    cacheDir: ".content-cache",
  },
  setup(options, nuxt) {
    const manifestPath = join(nuxt.options.rootDir, options.cacheDir!, "version-manifest.json");

    // Hook into app:resolve to populate appConfig before it's finalized
    nuxt.hook("app:resolve", () => {
      if (!existsSync(manifestPath)) {
        console.warn(
          "[version-config] No version manifest found. Run build after configuring GitHub tags source.",
        );
        return;
      }

      try {
        const manifest = JSON.parse(
          readFileSync(manifestPath, "utf-8"),
        ) as VersionManifest;

        // Merge into appConfig
        nuxt.options.appConfig = nuxt.options.appConfig || {};
        nuxt.options.appConfig.version = {
          versions: manifest.versions,
          latest: manifest.latest,
          current: "", // Will be determined from URL at runtime
        };

        console.log(
          `[version-config] Loaded ${manifest.versions.length} versions, latest: ${manifest.latest}`,
        );
      } catch (err) {
        console.error("[version-config] Failed to read version manifest:", err);
      }
    });
  },
});
