import components from "#config/components";

const INDENT = "  ";

const quoted = (name: string) => JSON.stringify(name);

/**
 * Render the generated `ComponentEvents` registry from the component config's
 * per-component `events` lists.
 *
 * Every component is emitted as a key holding its native-event emits contract
 * in Vue object-emits form — each listed event mapped to a payload tuple whose
 * type is the DOM's own (`GlobalEventHandlersEventMap`). Components with no
 * events hold `{}` so every emits type can index its entry unconditionally.
 *
 * The registry is generated rather than derived type-level from the config
 * because `defineEmits` needs `@vue/compiler-sfc` to statically resolve the
 * emits type's keys, and the macro resolver cannot fold a `typeof`-const query
 * into finite keys — a literal interface indexed by component name
 * (`ComponentEvents["button"]`) is the shape it understands.
 */
export function generateEventsTypes(): string {
  const componentEntry = (name: string, list: readonly string[]) => {
    if (!list.length) {
      return `${INDENT}${quoted(name)}: {};`;
    }
    const lines = list.map(
      (event) =>
        `${INDENT}${INDENT}${quoted(event)}: [event: GlobalEventHandlersEventMap[${quoted(event)}]];`,
    );
    return [`${INDENT}${quoted(name)}: {`, ...lines, `${INDENT}};`].join("\n");
  };

  return [
    "// Generated by the `events` module — do not edit.",
    "",
    "export interface ComponentEvents {",
    ...Object.entries({ ...components.elements, ...components.compounds }).map(
      ([name, { events }]) => componentEntry(name, events),
    ),
    "}",
    "",
  ].join("\n");
}
