import type { ModifiersInput } from "#modules/contracts/types";

import { addTypeTemplate, createResolver, defineNuxtModule } from "@nuxt/kit";
import { generateAriaTypes } from "#modules/contracts/aria";
import { generateEventsTypes } from "#modules/contracts/events";
import { generateModifierTypes } from "#modules/contracts/modifiers";
import devModifiers from "#stubs/modifiers";

/** Options accepted under the `modifiers` key in `nuxt.config`. */
export type ModuleOptions = ModifiersInput;

const normalize = (path: string) => path.replace(/[/\\]+$/, "");

/**
 * Single build-time generation plane for the component contracts, emitted as
 * one `types/contracts.d.ts`. Three sections derive from `config/components`
 * and the WAI-ARIA spec:
 *
 * - `GlobalAria` / `RoleAria` / `ProhibitedAria` — the aria surface, derived
 *   from the `aria-query` spec. This feeds the config (`role: keyof RoleAria`)
 *   rather than reading it, so it is emitted first.
 * - `ComponentEvents` — the native-event emits contract, from the per-component
 *   `events` lists.
 * - `ComponentModifiers` — the variant-axis registry, from the user-authored
 *   `modifiers` schema (the only consumer-configured section).
 *
 * The three were separate modules; they share `config/components` as their
 * source of truth, so they collapse into one module and one output file.
 */
export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: "contracts",
    configKey: "modifiers",
  },
  defaults: {},
  setup(options, nuxt) {
    const { resolve } = createResolver(import.meta.url);

    // Simulate a consumer config only while developing foundation itself. When
    // the layer is extended, rootDir is the consumer's app and the dev stub is
    // ignored in favour of their real `modifiers` config.
    const isFoundationRoot =
      normalize(nuxt.options.rootDir) === normalize(resolve("../.."));
    const schema = isFoundationRoot ? { ...devModifiers, ...options } : options;

    addTypeTemplate({
      filename: "types/contracts.d.ts",
      write: true,
      getContents: () =>
        [
          "// Generated by the `contracts` module — do not edit.",
          "",
          generateAriaTypes(),
          generateEventsTypes(),
          generateModifierTypes(schema),
        ].join("\n"),
    });
  },
});
