import { defineElement } from "@foundation/untheme/config";

export default {
  a: defineElement("flexbox", "interactive", "disabled"),
  accordionContent: defineElement(),
  accordionHeader: defineElement(),
  accordionItem: defineElement(),
  accordionRoot: defineElement(),
  accordionTrigger: defineElement(
    "flexbox",
    "interactive",
    "selected",
    "animated",
  ),
  accordionTriggerContent: defineElement("flexbox"),
  article: defineElement(),
  aside: defineElement("positioned", "overflow"),
  avatarFallback: defineElement("flexbox"),
  avatarImage: defineElement(),
  avatarRoot: defineElement("overflow"),
  blockquote: defineElement(),
  breadcrumbsRoot: defineElement(),
  breadcrumbsList: defineElement("flexbox"),
  breadcrumbsItem: defineElement("flexbox"),
  breadcrumbsLink: defineElement("flexbox", "interactive", "disabled", "animated"),
  breadcrumbsCurrent: defineElement("flexbox"),
  button: defineElement("interactive", "animated", "positioned", "transform"),
  caption: defineElement("flexbox"),
  card: defineElement("overflow"),
  chip: defineElement("flexbox", "textflow"),
  checkboxRoot: defineElement("interactive", "disabled", "selected", "animated"),
  checkboxIndicator: defineElement("flexbox", "animated"),
  code: defineElement(),
  del: defineElement(),
  em: defineElement(),
  footer: defineElement("grid", "flexbox"),
  group: defineElement("flexbox"),
  h1: defineElement("scrollable"),
  h2: defineElement("scrollable"),
  h3: defineElement("scrollable"),
  h4: defineElement("scrollable"),
  h5: defineElement("scrollable"),
  h6: defineElement("scrollable"),
  header: defineElement("grid"),
  hr: defineElement(),
  icon: defineElement("flexbox"),
  img: defineElement(),
  input: defineElement(),
  kbd: defineElement("flexbox"),
  label: defineElement(),
  li: defineElement(),
  link: defineElement("flexbox", "interactive"),
  listboxContent: defineElement("flexbox"),
  listboxItem: defineElement(
    "flexbox",
    "interactive",
    "disabled",
    "selected",
    "animated",
  ),
  listboxRoot: defineElement(),
  main: defineElement("grid"),
  nav: defineElement(),
  ol: defineElement(),
  p: defineElement(),
  pre: defineElement("overflow"),
  section: defineElement("grid", "flexbox"),
  selectRoot: defineElement(),
  selectTrigger: defineElement("flexbox", "interactive", "animated"),
  selectContent: defineElement("positioned", "animated", "overflow"),
  selectItem: defineElement("interactive", "selected", "animated"),
  strong: defineElement(),
  table: defineElement("table"),
  thead: defineElement(),
  tbody: defineElement(),
  tr: defineElement(),
  th: defineElement("table"),
  td: defineElement("table"),
  tabsContent: defineElement(),
  tabsList: defineElement("flexbox"),
  tabsRoot: defineElement(),
  tabsTrigger: defineElement("flexbox", "interactive", "selected", "animated"),
  tagsInputRoot: defineElement("flexbox", "overflow"),
  tagsInputItem: defineElement("flexbox", "animated"),
  tagsInputItemText: defineElement(),
  tagsInputItemDelete: defineElement("flexbox", "interactive", "animated"),
  tagsInputInput: defineElement(),
  tagsInputClear: defineElement("interactive", "animated"),

  // Tree
  treeRoot: defineElement("overflow"),
  treeBranch: defineElement("flexbox", "interactive", "open", "animated"),
  treeBranchContent: defineElement("flexbox"),
  treeLeaf: defineElement(
    "flexbox",
    "interactive",
    "selected",
    "animated",
    "disabled",
  ),
  treeLeafContent: defineElement("flexbox", "interactive", "animated"),
  tooltipContent: defineElement("positioned", "animated", "flexbox"),
  dialogOverlay: defineElement("positioned", "animated"),
  dialogContent: defineElement("positioned", "animated", "transform"),
  popoverTrigger: defineElement("interactive", "animated"),
  popoverContent: defineElement("positioned", "animated", "overflow"),
  popoverArrow: defineElement(),
  popoverClose: defineElement("interactive", "animated"),
  navigatorRoot: defineElement("flexbox", "positioned"),
  navigatorList: defineElement("flexbox"),
  navigatorItem: defineElement(),
  navigatorTrigger: defineElement("flexbox", "interactive", "open", "animated"),
  navigatorLink: defineElement("flexbox", "interactive", "animated"),
  navigatorContent: defineElement("positioned", "animated", "overflow"),
  navigatorViewport: defineElement("positioned", "overflow"),
  navigatorViewportWrapper: defineElement("positioned", "flexbox"),
  navigatorIndicator: defineElement("positioned", "animated"),
  navigatorGrid: defineElement("grid"),
  navigatorCard: defineElement("flexbox", "interactive", "animated"),
  navigatorFeatured: defineElement("flexbox", "interactive", "animated"),
  ul: defineElement(),
};
