import { createStub } from "#test/stubs/factories";

// Stub keys match the import binding names components use (VTU resolves stubs
// against the parent's setupState bindings, kebab/Pascal variants of the key).
// One entry per element wrapper at components/common root, tagged with the
// element it wraps so stubbed DOM keeps its shape.
export const commonStubs = {
  Alert: createStub("Alert"),
  Anchor: createStub("Anchor", "a"),
  Article: createStub("Article", "article"),
  Aside: createStub("Aside", "aside"),
  Banner: createStub("Banner"),
  Blockquote: createStub("Blockquote", "blockquote"),
  Button: createStub("Button", "button"),
  Caption: createStub("Caption"),
  Card: createStub("Card"),
  Chip: createStub("Chip", "button"),
  Code: createStub("Code", "code"),
  Container: createStub("Container"),
  Del: createStub("Del", "del"),
  Em: createStub("Em", "em"),
  Fieldset: createStub("Fieldset", "fieldset"),
  Footer: createStub("Footer", "footer"),
  Form: createStub("Form", "form"),
  Group: createStub("Group"),
  H1: createStub("H1", "h1"),
  H2: createStub("H2", "h2"),
  H3: createStub("H3", "h3"),
  H4: createStub("H4", "h4"),
  H5: createStub("H5", "h5"),
  H6: createStub("H6", "h6"),
  Header: createStub("Header", "header"),
  Hr: createStub("Hr", "hr"),
  Icon: createStub("Icon", "i"),
  Img: createStub("Img", "img"),
  Input: createStub("Input", "input"),
  Kbd: createStub("Kbd", "kbd"),
  Label: createStub("Label", "label"),
  Li: createStub("Li", "li"),
  Main: createStub("Main", "main"),
  Nav: createStub("Nav", "nav"),
  Ol: createStub("Ol", "ol"),
  P: createStub("P", "p"),
  Pre: createStub("Pre", "pre"),
  Section: createStub("Section", "section"),
  Span: createStub("Span", "span"),
  Strong: createStub("Strong", "strong"),
  Table: createStub("Table", "table"),
  Tbody: createStub("Tbody", "tbody"),
  Td: createStub("Td", "td"),
  Textarea: createStub("Textarea", "textarea"),
  Th: createStub("Th", "th"),
  Thead: createStub("Thead", "thead"),
  Tr: createStub("Tr", "tr"),
  Ul: createStub("Ul", "ul"),
} as const;
