import { defineUntheme } from "../src/config";

export default defineUntheme({
  roles: {
    a: {
      text: "sys-primary",
      "text-hover": "sys-primary-hover",
      "text-active": "sys-primary-active",
      "font-size": "ref-text-base",
      "font-weight": "ref-font-normal",
      "line-height": "ref-leading-normal",
      "text-decoration": "ref-decoration-none",
      cursor: "ref-cursor-pointer",
    },
    button: {
      cursor: "ref-cursor-pointer",
      "padding-left": "ref-spacing-lg",
      "padding-right": "ref-spacing-lg",
      "padding-top": "ref-spacing-md",
      "padding-bottom": "ref-spacing-md",
      "outline-color": "sys-focus",
      "outline-width": "ref-outline-width-medium",
      "font-weight": "ref-font-bold",
      "font-weight-hover": "ref-font-bold",
      "font-weight-active": "ref-font-bold",
      "font-weight-focus": "ref-font-bold",
      "background-focus": "sys-hover",
      "box-shadow-focus": "ref-shadow-focus-inset",
    },
    group: {
      display: "ref-display-inline-flex",
      "flex-direction": "ref-flex-row",
      "align-items": "ref-align-center",
      gap: "ref-none",
    },
    "accordion-trigger": {
      background: "ref-color-transparent",
      text: "sys-on-surface-variant",
      cursor: "ref-cursor-pointer",
      "font-size": "ref-text-base",
      "font-weight": "ref-font-bold",
      "text-align": "ref-align-start",
      display: "ref-display-flex",
      "align-items": "ref-align-center",
      "justify-content": "ref-justify-between",
      gap: "ref-spacing-xs",
      width: "ref-full",
      "padding-left": "ref-spacing-md",
      "padding-right": "ref-spacing-md",
      "padding-top": "ref-spacing-sm",
      "padding-bottom": "ref-spacing-sm",
      "font-weight-selected": "ref-font-bold",
      "font-weight-hover": "ref-font-bold",
      "font-weight-active": "ref-font-bold",
      "font-weight-focus": "ref-font-bold",
      "font-weight-selected-hover": "ref-font-bold",
      "font-weight-selected-active": "ref-font-bold",
      "font-weight-selected-focus": "ref-font-bold",
      "background-focus": "sys-hover",
      "box-shadow-focus": "ref-shadow-focus-inset",
      "background-selected-focus": "sys-hover",
      "box-shadow-selected-focus": "ref-shadow-focus-inset",
    },
    "accordion-content": {
      background: "ref-color-transparent",
      text: "sys-on-surface",
      "font-size": "ref-text-base",
    },
    aside: {
      background: "sys-surface",
      text: "sys-on-surface",
      "border-color": "ref-color-transparent",
      "border-right-width": "ref-border-width-thin",
      "border-right-color": "sys-outline-variant",
      "border-right-style": "ref-border-style-solid",
      width: "ref-width-sm",
      height: "ref-height-full",
      "box-shadow": "ref-shadow-sm",
    },
    "avatar-root": {
      width: "ref-spacing-2xl",
      height: "ref-spacing-2xl",
      "border-top-left-radius": "ref-radius-full",
      "border-top-right-radius": "ref-radius-full",
      "border-bottom-right-radius": "ref-radius-full",
      "border-bottom-left-radius": "ref-radius-full",
      "overflow-x": "ref-overflow-hidden",
      "overflow-y": "ref-overflow-hidden",
      display: "ref-display-inline-flex",
    },
    "avatar-image": {
      width: "ref-full",
      height: "ref-full",
      "object-fit": "ref-object-cover",
      display: "ref-display-block",
    },
    "avatar-fallback": {
      width: "ref-full",
      height: "ref-full",
      background: "sys-surface-container",
      text: "sys-on-surface",
      display: "ref-display-inline-flex",
      "align-items": "ref-align-center",
      "justify-content": "ref-justify-center",
      "font-size": "ref-text-base",
      "font-weight": "ref-font-medium",
    },
    header: {
      background: "sys-surface",
      text: "sys-on-surface",
      gap: "ref-spacing-md",
      display: "ref-display-grid",
      "grid-template-columns": "ref-layout-trifold",
      "grid-column": "ref-grid-col-span-all",
      "align-items": "ref-align-center",
      "border-bottom-style": "ref-border-style-solid",
      "border-bottom-width": "ref-border-width-thin",
      "border-bottom-color": "sys-outline-variant",
    },
    icon: {
      text: "ref-color-current",
      opacity: "ref-opacity-100",
      display: "ref-display-inline-flex",
      "align-items": "ref-align-center",
      "justify-content": "ref-justify-center",
      width: "ref-width-1em",
      height: "ref-height-1em",
    },
    "listbox-root": {
      background: "ref-color-transparent",
    },
    "listbox-content": {
      background: "ref-color-transparent",
      display: "ref-display-flex",
      "flex-direction": "ref-flex-col",
      gap: "ref-spacing-none",
    },
    "listbox-item": {
      background: "ref-color-transparent",
      text: "sys-on-surface-variant",
      "text-hover": "sys-on-surface",
      "text-active": "sys-primary",
      "text-selected": "sys-primary",
      "text-selected-hover": "sys-primary",
      "background-selected": "sys-hover",
      "background-selected-hover": "sys-hover",
      "box-shadow-selected": "ref-shadow-border-left",
      "box-shadow-selected-hover": "ref-shadow-border-left",
      "box-shadow-selected-active": "ref-shadow-border-left",
      "border-color": "ref-color-transparent",
      "padding-left": "ref-spacing-md",
      "padding-right": "ref-spacing-md",
      "padding-top": "ref-spacing-xs",
      "padding-bottom": "ref-spacing-xs",
      cursor: "ref-cursor-pointer",
      "cursor-disabled": "ref-cursor-not-allowed",
      "font-size": "ref-text-base",
      "font-weight": "ref-font-bold",
      "font-weight-hover": "ref-font-bold",
      "font-weight-active": "ref-font-bold",
      "font-weight-focus": "ref-font-bold",
      "font-weight-selected": "ref-font-bold",
      "font-weight-selected-hover": "ref-font-bold",
      "font-weight-selected-active": "ref-font-bold",
      "font-weight-selected-focus": "ref-font-bold",
      "text-selected-active": "sys-primary",
      "text-selected-focus": "sys-primary",
      display: "ref-display-flex",
      "align-items": "ref-align-center",
      "justify-content": "ref-justify-between",
      gap: "ref-spacing-sm",
      "background-focus": "sys-hover",
      "box-shadow-focus": "ref-shadow-focus-inset",
      "background-selected-focus": "sys-hover",
      "box-shadow-selected-focus": "ref-shadow-border-left-focus",
    },
    "tabs-root": {
      background: "ref-color-transparent",
    },
    "tabs-list": {
      background: "ref-color-transparent",
      display: "ref-display-flex",
      "flex-direction": "ref-flex-row",
      gap: "ref-spacing-none",
      "border-bottom-width": "ref-border-width-thin",
      "border-bottom-color": "sys-outline-variant",
      "border-bottom-style": "ref-border-style-solid",
    },
    "tabs-trigger": {
      background: "ref-color-transparent",
      text: "sys-on-surface-variant",
      "text-hover": "sys-on-surface",
      "text-active": "sys-primary",
      "text-selected": "sys-primary",
      "text-selected-hover": "sys-primary",
      "text-selected-active": "sys-primary",
      "text-selected-focus": "sys-primary",
      "box-shadow-selected": "ref-shadow-border-bottom",
      "box-shadow-selected-hover": "ref-shadow-border-bottom",
      "box-shadow-selected-active": "ref-shadow-border-bottom",
      cursor: "ref-cursor-pointer",
      "font-size": "ref-text-base",
      "font-weight": "ref-font-bold",
      "font-weight-hover": "ref-font-bold",
      "font-weight-active": "ref-font-bold",
      "font-weight-focus": "ref-font-bold",
      "font-weight-selected": "ref-font-bold",
      "font-weight-selected-hover": "ref-font-bold",
      "font-weight-selected-active": "ref-font-bold",
      "font-weight-selected-focus": "ref-font-bold",
      "padding-left": "ref-spacing-lg",
      "padding-right": "ref-spacing-lg",
      "padding-top": "ref-spacing-md",
      "padding-bottom": "ref-spacing-md",
      display: "ref-display-flex",
      "align-items": "ref-align-center",
      "justify-content": "ref-justify-center",
      "background-focus": "sys-hover",
      "box-shadow-focus": "ref-shadow-focus-inset",
      "background-selected-focus": "sys-hover",
      "box-shadow-selected-focus": "ref-shadow-border-bottom-focus",
    },
    "tabs-content": {
      background: "ref-color-transparent",
      text: "sys-on-surface",
      "font-size": "ref-text-base",
    },
    main: {
      background: "sys-surface",
      text: "sys-on-surface",
      height: "ref-viewport-height",
      "min-height": "ref-viewport-height",
      "max-height": "ref-viewport-height",
    },
    section: {
      background: "ref-color-transparent",
      text: "sys-on-surface",
    },
    article: {
      background: "ref-color-transparent",
      text: "sys-on-surface",
      "max-width": "ref-width-prose",
      "line-height": "ref-leading-relaxed",
      display: "ref-display-block",
      "padding-top": "ref-spacing-lg",
      "padding-right": "ref-spacing-lg",
      "padding-bottom": "ref-spacing-lg",
      "padding-left": "ref-spacing-lg",
    },
    nav: {
      background: "ref-color-transparent",
      text: "sys-on-surface",
    },
    footer: {
      background: "sys-surface",
      text: "sys-on-surface",
      gap: "ref-spacing-md",
      display: "ref-display-grid",
      "grid-template-columns": "ref-layout-trifold",
      "grid-column": "ref-grid-col-span-all",
      "align-items": "ref-align-center",
      "border-top-style": "ref-border-style-solid",
      "border-top-width": "ref-border-width-thin",
      "border-top-color": "sys-outline-variant",
    },
    p: {
      text: "sys-on-surface",
      "font-size": "ref-text-base",
      "font-weight": "ref-font-normal",
      "line-height": "ref-leading-normal",
      display: "ref-display-block",
      "margin-top": "ref-spacing-base",
      "margin-bottom": "ref-spacing-base",
    },
    h1: {
      text: "sys-on-surface",
      "font-size": "ref-text-4xl",
      "font-weight": "ref-font-bold",
      "line-height": "ref-leading-tighter",
      display: "ref-display-block",
      "margin-top": "ref-spacing-none",
      "margin-bottom": "ref-spacing-xl",
    },
    h2: {
      text: "sys-on-surface",
      "font-size": "ref-text-2xl",
      "font-weight": "ref-font-bold",
      "line-height": "ref-leading-snug",
      display: "ref-display-block",
      "margin-top": "ref-spacing-2xl",
      "margin-bottom": "ref-spacing-lg",
    },
    h3: {
      text: "sys-on-surface",
      "font-size": "ref-text-xl",
      "font-weight": "ref-font-semibold",
      "line-height": "ref-leading-cozy",
      display: "ref-display-block",
      "margin-top": "ref-spacing-xl",
      "margin-bottom": "ref-spacing-sm",
    },
    h4: {
      text: "sys-on-surface",
      "font-size": "ref-text-base",
      "font-weight": "ref-font-semibold",
      "line-height": "ref-leading-normal",
      display: "ref-display-block",
      "margin-top": "ref-spacing-lg",
      "margin-bottom": "ref-spacing-xs",
    },
    h5: {
      text: "sys-on-surface-variant",
      "font-size": "ref-text-base",
      "font-weight": "ref-font-semibold",
      "line-height": "ref-leading-normal",
      display: "ref-display-block",
      "margin-top": "ref-spacing-lg",
      "margin-bottom": "ref-spacing-xs",
    },
    h6: {
      text: "sys-on-surface-variant",
      "font-size": "ref-text-base",
      "font-weight": "ref-font-medium",
      "line-height": "ref-leading-normal",
      display: "ref-display-block",
      "margin-top": "ref-spacing-lg",
      "margin-bottom": "ref-spacing-xs",
    },
    code: {
      text: "sys-on-surface",
      background: "sys-hover",
      "font-family": "ref-font-mono",
      "font-size": "ref-text-sm",
      "padding-top": "ref-spacing-2xs",
      "padding-right": "ref-spacing-xs",
      "padding-bottom": "ref-spacing-2xs",
      "padding-left": "ref-spacing-xs",
      "border-top-width": "ref-border-width-thin",
      "border-right-width": "ref-border-width-thin",
      "border-bottom-width": "ref-border-width-thin",
      "border-left-width": "ref-border-width-thin",
      "border-top-color": "sys-outline-variant",
      "border-right-color": "sys-outline-variant",
      "border-bottom-color": "sys-outline-variant",
      "border-left-color": "sys-outline-variant",
      "border-top-style": "ref-border-style-solid",
      "border-right-style": "ref-border-style-solid",
      "border-bottom-style": "ref-border-style-solid",
      "border-left-style": "ref-border-style-solid",
      display: "ref-display-inline-block",
    },
    pre: {
      text: "sys-on-surface",
      background: "sys-hover",
      "font-family": "ref-font-mono",
      "font-size": "ref-text-sm",
      "padding-top": "ref-spacing-md",
      "padding-right": "ref-spacing-md",
      "padding-bottom": "ref-spacing-md",
      "padding-left": "ref-spacing-md",
      "border-top-width": "ref-border-width-thin",
      "border-right-width": "ref-border-width-thin",
      "border-bottom-width": "ref-border-width-thin",
      "border-left-width": "ref-border-width-thin",
      "border-top-color": "sys-outline-variant",
      "border-right-color": "sys-outline-variant",
      "border-bottom-color": "sys-outline-variant",
      "border-left-color": "sys-outline-variant",
      "border-top-style": "ref-border-style-solid",
      "border-right-style": "ref-border-style-solid",
      "border-bottom-style": "ref-border-style-solid",
      "border-left-style": "ref-border-style-solid",
      display: "ref-display-block",
      "overflow-x": "ref-overflow-auto",
      "margin-top": "ref-spacing-base",
      "margin-bottom": "ref-spacing-base",
    },
    strong: {
      "font-weight": "ref-font-bold",
      display: "ref-display-inline",
    },
    em: {
      "font-style": "ref-font-italic",
      display: "ref-display-inline",
    },
    blockquote: {
      text: "sys-on-surface-variant",
      "font-style": "ref-font-italic",
      "border-left-width": "ref-border-width-thick",
      "border-left-color": "sys-outline-variant",
      "border-left-style": "ref-border-style-solid",
      "padding-left": "ref-spacing-lg",
      "margin-top": "ref-spacing-xl",
      "margin-bottom": "ref-spacing-xl",
      display: "ref-display-block",
    },
    hr: {
      "border-top-width": "ref-border-width-thin",
      "border-top-color": "sys-outline-variant",
      "border-top-style": "ref-border-style-solid",
      "margin-top": "ref-spacing-2xl",
      "margin-bottom": "ref-spacing-2xl",
      display: "ref-display-block",
    },
    ul: {
      "list-style-type": "ref-list-disc",
      "padding-left": "ref-spacing-xl",
      "margin-top": "ref-spacing-base",
      "margin-bottom": "ref-spacing-base",
      display: "ref-display-block",
    },
    ol: {
      "list-style-type": "ref-list-decimal",
      "padding-left": "ref-spacing-xl",
      "margin-top": "ref-spacing-base",
      "margin-bottom": "ref-spacing-base",
      display: "ref-display-block",
    },
    li: {
      display: "ref-display-list-item",
      "margin-top": "ref-spacing-xs",
      "margin-bottom": "ref-spacing-xs",
    },
  },
});
