import type { ARIARoleDefinitionKey } from "aria-query";
import { roles } from "aria-query";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const OUTPUT = fileURLToPath(
  new URL("../app/types/aria-spec.ts", import.meta.url),
);

const INDENT = "  ";

const strip = (prop: string) => prop.replace(/^aria-/, "");

const quoted = (name: string) => JSON.stringify(name);

/**
 * The ARIA global states and properties: the base `roletype` role's props,
 * which every role inherits. aria-query folds these into each role's `props`,
 * so they double as the set to subtract for a role's own delta.
 */
function globalAttributes(): string[] {
  const roletype = roles.get("roletype");
  return Object.keys(roletype?.props ?? {})
    .map(strip)
    .sort();
}

/**
 * Render the `GlobalAria` union, `RoleAria` registry, and `ProhibitedAria` map
 * from the WAI-ARIA spec data in `aria-query`.
 *
 * The aria surface of a role is fixed by the standard, so the output only
 * changes when the `aria-query` dependency does — it is committed as
 * `app/types/aria-spec.ts` rather than generated at build time.
 *
 * `GlobalAria` is the base props valid on every role. Each concrete (non-
 * abstract) role maps in `RoleAria` to its supported props *minus* those globals
 * — the delta it adds — or `never` when it adds nothing. `ProhibitedAria` maps
 * each role to the props the spec forbids it (e.g. `generic` prohibits naming);
 * `AriaProps` excludes these from the global+role surface, so a role cannot
 * carry an attribute the standard bans even when it is a global. Names are
 * `aria-`-stripped to the bare authoring form the `AriaProps` mapped type
 * re-prefixes; names absent from Vue's `AriaAttributes` are dropped downstream
 * by `& keyof AllAria`.
 */
function generateAriaTypes(): string {
  const globals = globalAttributes();
  const globalSet = new Set(globals);

  const concreteRoles = [...roles.entries()]
    .filter(([, def]) => !def.abstract)
    .map(([name]) => name)
    .sort();

  const roleEntry = (name: ARIARoleDefinitionKey) => {
    const specific = Object.keys(roles.get(name)?.props ?? {})
      .map(strip)
      .filter((prop) => !globalSet.has(prop))
      .sort();
    const value = specific.length ? specific.map(quoted).join(" | ") : "never";
    return `${INDENT}${quoted(name)}: ${value};`;
  };

  const prohibitedEntry = (name: ARIARoleDefinitionKey) => {
    // `@types/aria-query` types `prohibitedProps` as a map, but the runtime
    // value is an array of prop names; normalize both shapes to name keys.
    const raw = roles.get(name)?.prohibitedProps;
    const names = Array.isArray(raw) ? [...raw] : Object.keys(raw ?? {});
    const prohibited = names.map(strip).sort();
    const value = prohibited.length
      ? prohibited.map(quoted).join(" | ")
      : "never";
    return `${INDENT}${quoted(name)}: ${value};`;
  };

  const globalUnion = globals
    .map((name) => `${INDENT}| ${quoted(name)}`)
    .join("\n");

  return [
    "// Generated by `scripts/aria.ts` from the WAI-ARIA spec data in `aria-query`",
    "// — do not edit. Regenerate with `make generate` when `aria-query` bumps.",
    "",
    `export type GlobalAria =\n${globalUnion};`,
    "",
    "export interface RoleAria {",
    ...concreteRoles.map(roleEntry),
    "}",
    "",
    "export interface ProhibitedAria {",
    ...concreteRoles.map(prohibitedEntry),
    "}",
    "",
  ].join("\n");
}

writeFileSync(OUTPUT, generateAriaTypes());
console.log(`wrote ${OUTPUT}`);
