import { defineNuxtPlugin } from "#app";
import type { LogLevel, LogEntry } from "../src/types";
import { meetsLevel } from "../src/levels";
import { isLogEntry, isLogLevel } from "../src/guards";

// @ts-ignore — virtual module generated by the crucible Nuxt module
import crucibleConfig from "#build/crucible.config.mjs";

const batch: LogEntry[] = [];
let flushTimer: ReturnType<typeof setTimeout> | null = null;

const flush = (): void => {
  if (batch.length === 0) return;
  const entries = batch.splice(0, batch.length);
  const body = JSON.stringify(entries);

  if (navigator.sendBeacon("/api/crucible", body)) return;
  fetch("/api/crucible", {
    method: "POST",
    body,
    headers: { "Content-Type": "application/json" },
    keepalive: true,
  }).catch(() => {});
};

const scheduleFlush = (): void => {
  if (flushTimer) return;
  flushTimer = setTimeout(() => {
    flushTimer = null;
    flush();
  }, 5000);
};

export default defineNuxtPlugin({
  name: "crucible:client",
  setup(nuxtApp) {
    const hookMap = crucibleConfig.hookLevels as Record<string, string>;
    const minimum = isLogLevel(crucibleConfig.minLevel) ? crucibleConfig.minLevel : "debug";

    window.addEventListener("beforeunload", flush);

    nuxtApp.hooks.afterEach((event) => {
      const name = String(event.name);

      let entry: LogEntry;

      if (name.startsWith("log:") && isLogEntry(event.args[0])) {
        entry = { ...event.args[0], source: "client" };
      } else {
        const mapped = hookMap[name] || "debug";
        const level: LogLevel = isLogLevel(mapped) ? mapped : "debug";
        if (!meetsLevel(level, minimum)) return;

        entry = {
          level,
          message: name,
          timestamp: Date.now(),
          hook: name,
          source: "client",
        };
      }

      if (!meetsLevel(entry.level, minimum)) return;

      batch.push(entry);
      scheduleFlush();
    });
  },
});
