import { defineEventHandler, readBody, readRawBody, getRequestHeader } from "h3";
import { useNitroApp } from "nitropack/runtime";
import type { LogLevel, LogEntry } from "../src/types";
import { meetsLevel } from "../src/levels";
import { isLogEntry, isLogLevel } from "../src/guards";

// @ts-ignore — virtual module generated by the crucible Nuxt module
import crucibleConfig from "#build/crucible.config.mjs";

export interface CrucibleHandler {
  write: (entry: LogEntry) => void | Promise<void>;
}

let initialized = false;

export const defineCrucibleHandler = (handler: CrucibleHandler) => {
  const hookMap = crucibleConfig.hookLevels as Record<string, string>;
  const minimum = isLogLevel(crucibleConfig.minLevel) ? crucibleConfig.minLevel : "debug";

  return defineEventHandler(async (event) => {
    // Idempotently register afterEach on the Nitro hook system
    if (!initialized) {
      initialized = true;
      const nitro = useNitroApp();
      nitro.hooks.afterEach((hookEvent: { name: string | symbol; args: unknown[] }) => {
        const name = String(hookEvent.name);
        const mapped = hookMap[name] || "debug";
        const level: LogLevel = isLogLevel(mapped) ? mapped : "debug";
        if (!meetsLevel(level, minimum)) return;

        handler.write({
          level,
          message: name,
          timestamp: Date.now(),
          hook: name,
          source: "server",
        });
      });
    }

    // Receive client log batches
    const contentType = getRequestHeader(event, "content-type") || "";

    let entries: unknown[];
    if (contentType.includes("application/json")) {
      const body = await readBody(event);
      entries = Array.isArray(body) ? body : [];
    } else {
      const raw = await readRawBody(event, "utf-8");
      if (!raw) return { ok: true };
      try {
        const parsed: unknown = JSON.parse(raw);
        entries = Array.isArray(parsed) ? parsed : [];
      } catch {
        return { ok: true };
      }
    }

    for (const raw of entries) {
      if (isLogEntry(raw)) {
        await handler.write({ ...raw, source: "client" });
      }
    }

    return { ok: true };
  });
};
