/**
 * The native-event emits registry, generated by the `events` module from the
 * per-component `events` lists in `config/components`: each component keys its
 * contract in Vue object-emits form, with payloads typed from the DOM's own
 * event map (`click: [event: PointerEvent]`). Components with no listed events
 * key `{}`, so every emits type can wire its entry unconditionally —
 * `type FooEmits = ComponentEvents["foo"] & { ... }`.
 *
 * Indexed with a literal (`ComponentEvents["foo"]`), never through a generic:
 * `@vue/compiler-sfc` must statically fold the emits keys for `defineEmits`,
 * and its resolver cannot substitute a type parameter inside an indexed
 * access.
 *
 * The contract is fulfilled by explicit re-emit: a component declares it via
 * `defineEmits` and re-emits each event from its root
 * (`@click="emit('click', $event)"`). The compiler checks that direction — an
 * `emit` call for an event the config does not list is an error.
 */
export type { ComponentEvents } from "#build/types/events";
